import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { AppLayout } from "@/components/layout/AppLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { RichTextEditor } from "@/components/documents/RichTextEditor";
import {
  FileText,
  Plus,
  Search,
  ArrowLeft,
  Save,
  Bot,
  Download,
  Mail,
  History,
  Send,
  RotateCcw,
  Loader2,
  Trash2,
  ExternalLink,
  Sparkles,
} from "lucide-react";
import { useLocation } from "wouter";

const BASE = import.meta.env.BASE_URL.replace(/\/$/, "");

interface DocumentListItem {
  id: number;
  title: string;
  department: string | null;
  status: string;
  botName: string | null;
  currentVersion: number;
  createdAt: string;
  updatedAt: string;
}

interface DocumentFull extends DocumentListItem {
  content: unknown;
  versionHistory: Array<{
    version: number;
    title: string;
    content: unknown;
    editedBy: string;
    createdAt: string;
  }>;
  botId: number | null;
  sessionId: number | null;
  clientId: number;
}

function DocumentList({
  onSelect,
  onCreate,
}: {
  onSelect: (id: number) => void;
  onCreate: () => void;
}) {
  const [, navigate] = useLocation();
  const [search, setSearch] = useState("");
  const [deptFilter, setDeptFilter] = useState("");

  const { data: docs = [], isLoading } = useQuery<DocumentListItem[]>({
    queryKey: ["documents", search, deptFilter],
    queryFn: async () => {
      const params = new URLSearchParams();
      if (search) params.set("search", search);
      if (deptFilter) params.set("department", deptFilter);
      const res = await fetch(`${BASE}/api/documents?${params}`);
      if (!res.ok) throw new Error("Failed to fetch documents");
      return res.json();
    },
  });

  const departments = [...new Set(docs.map((d) => d.department).filter(Boolean))];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-display font-bold">Document Studio</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Create, edit, and manage documents generated by your bots
          </p>
        </div>
        <div className="flex gap-2">
          <Button onClick={() => navigate("/proposals")} variant="outline" className="gap-2">
            <Sparkles className="w-4 h-4" /> AI Proposal
          </Button>
          <Button onClick={onCreate} variant="glow" className="gap-2">
            <Plus className="w-4 h-4" /> New Document
          </Button>
        </div>
      </div>

      <div className="flex gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search documents..."
            className="pl-10"
          />
        </div>
        {departments.length > 0 && (
          <select
            value={deptFilter}
            onChange={(e) => setDeptFilter(e.target.value)}
            className="bg-background border border-border rounded-lg px-3 text-sm"
          >
            <option value="">All Departments</option>
            {departments.map((d) => (
              <option key={d} value={d!}>{d}</option>
            ))}
          </select>
        )}
      </div>

      {isLoading ? (
        <div className="flex justify-center py-12">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
        </div>
      ) : docs.length === 0 ? (
        <Card className="border-dashed border-2 border-border/50">
          <CardContent className="flex flex-col items-center justify-center py-16">
            <FileText className="w-12 h-12 text-muted-foreground mb-4" />
            <p className="text-lg font-display font-semibold mb-2">No documents yet</p>
            <p className="text-sm text-muted-foreground mb-4">
              Create your first document or let a bot generate one
            </p>
            <Button onClick={onCreate} variant="outline" className="gap-2">
              <Plus className="w-4 h-4" /> Create Document
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-3">
          {docs.map((doc) => (
            <Card
              key={doc.id}
              className="cursor-pointer hover:border-primary/50 transition-colors"
              onClick={() => onSelect(doc.id)}
            >
              <CardContent className="p-4 flex items-center gap-4">
                <FileText className="w-8 h-8 text-primary shrink-0" />
                <div className="flex-1 min-w-0">
                  <h3 className="font-semibold truncate">{doc.title}</h3>
                  <div className="flex items-center gap-2 mt-1 text-xs text-muted-foreground">
                    {doc.botName && (
                      <Badge variant="outline" className="text-[10px]">
                        <Bot className="w-3 h-3 mr-1" />
                        {doc.botName}
                      </Badge>
                    )}
                    {doc.department && (
                      <Badge variant="secondary" className="text-[10px]">{doc.department}</Badge>
                    )}
                    <span>v{doc.currentVersion}</span>
                    <span>
                      {new Date(doc.updatedAt).toLocaleDateString("en-US", {
                        month: "short",
                        day: "numeric",
                        year: "numeric",
                      })}
                    </span>
                  </div>
                </div>
                <Badge
                  variant={doc.status === "published" ? "default" : "outline"}
                  className="text-[10px] shrink-0"
                >
                  {doc.status}
                </Badge>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

function VersionHistoryPanel({
  versions,
  onRestore,
  isRestoring,
}: {
  versions: DocumentFull["versionHistory"];
  onRestore: (version: number) => void;
  isRestoring: boolean;
}) {
  if (!versions || versions.length === 0) {
    return (
      <div className="text-center py-8 text-muted-foreground">
        <History className="w-8 h-8 mx-auto mb-2 opacity-50" />
        <p className="text-sm">No previous versions</p>
      </div>
    );
  }

  const sorted = [...versions].sort((a, b) => b.version - a.version);

  return (
    <div className="space-y-2">
      <h3 className="text-sm font-tech text-muted-foreground uppercase tracking-wider px-1">
        Version History
      </h3>
      {sorted.map((v) => (
        <div key={v.version} className="p-3 rounded-lg border border-border/30 hover:border-border/60 transition-colors">
          <div className="flex items-center justify-between">
            <div>
              <span className="text-sm font-semibold">v{v.version}</span>
              <span className="text-xs text-muted-foreground ml-2">
                {v.editedBy.startsWith("bot:") ? v.editedBy.slice(4) : "Manual edit"}
              </span>
            </div>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => onRestore(v.version)}
              disabled={isRestoring}
              className="h-7 text-xs gap-1"
            >
              <RotateCcw className="w-3 h-3" /> Restore
            </Button>
          </div>
          <p className="text-xs text-muted-foreground mt-1">
            {new Date(v.createdAt).toLocaleString("en-US", {
              month: "short",
              day: "numeric",
              hour: "numeric",
              minute: "2-digit",
            })}
          </p>
        </div>
      ))}
    </div>
  );
}

function DocumentEditor({
  docId,
  onBack,
}: {
  docId: number;
  onBack: () => void;
}) {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const [showHistory, setShowHistory] = useState(false);
  const [showRevise, setShowRevise] = useState(false);
  const [reviseInstruction, setReviseInstruction] = useState("");
  const [emailTo, setEmailTo] = useState("");
  const [editedContent, setEditedContent] = useState<unknown>(null);
  const [editedTitle, setEditedTitle] = useState<string | null>(null);

  const { data: doc, isLoading } = useQuery<DocumentFull>({
    queryKey: ["document", docId],
    queryFn: async () => {
      const res = await fetch(`${BASE}/api/documents/${docId}`);
      if (!res.ok) throw new Error("Failed to fetch document");
      return res.json();
    },
  });

  const saveMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(`${BASE}/api/documents/${docId}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: editedTitle || doc?.title,
          content: editedContent || doc?.content,
        }),
      });
      if (!res.ok) throw new Error("Failed to save");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["document", docId] });
      queryClient.invalidateQueries({ queryKey: ["documents"] });
      toast({ title: "Document saved", description: "Your changes have been saved." });
      setEditedContent(null);
      setEditedTitle(null);
    },
  });

  const reviseMutation = useMutation({
    mutationFn: async (instruction: string) => {
      const res = await fetch(`${BASE}/api/documents/${docId}/revise`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ instruction }),
      });
      if (!res.ok) throw new Error("Revision failed");
      return res.json();
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["document", docId] });
      setReviseInstruction("");
      setShowRevise(false);
      toast({
        title: "Document revised",
        description: `${data.revisedBy} has updated the document.`,
      });
    },
  });

  const restoreMutation = useMutation({
    mutationFn: async (version: number) => {
      const res = await fetch(`${BASE}/api/documents/${docId}/restore-version`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ version }),
      });
      if (!res.ok) throw new Error("Restore failed");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["document", docId] });
      toast({ title: "Version restored" });
    },
  });

  const deleteMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(`${BASE}/api/documents/${docId}`, { method: "DELETE" });
      if (!res.ok) throw new Error("Delete failed");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["documents"] });
      onBack();
      toast({ title: "Document deleted" });
    },
  });

  const emailMutation = useMutation({
    mutationFn: async (to: string) => {
      const res = await fetch(`${BASE}/api/documents/${docId}/email`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ to }),
      });
      if (!res.ok) throw new Error("Email failed");
      return res.json();
    },
    onSuccess: () => {
      setEmailTo("");
      toast({ title: "Document emailed" });
    },
    onError: () => {
      toast({ title: "Email failed", description: "Check your email integration settings.", variant: "destructive" });
    },
  });

  const notionMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(`${BASE}/api/documents/${docId}/push-notion`, { method: "POST" });
      if (!res.ok) throw new Error("Notion push failed");
      return res.json();
    },
    onSuccess: (data) => {
      toast({
        title: "Pushed to Notion",
        description: data.url ? "Document created in Notion" : "Check Notion integration",
      });
    },
    onError: () => {
      toast({ title: "Notion push failed", description: "Check your Notion integration.", variant: "destructive" });
    },
  });

  if (isLoading || !doc) {
    return (
      <div className="flex justify-center py-20">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  const hasUnsavedChanges = editedContent !== null || editedTitle !== null;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="sm" onClick={onBack} className="gap-1">
            <ArrowLeft className="w-4 h-4" /> Back
          </Button>
          <Badge variant="outline" className="text-[10px]">v{doc.currentVersion}</Badge>
          {doc.botName && (
            <Badge variant="secondary" className="text-[10px] gap-1">
              <Bot className="w-3 h-3" /> {doc.botName}
            </Badge>
          )}
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setShowHistory(!showHistory)}
            className={`gap-1 ${showHistory ? "text-primary" : ""}`}
          >
            <History className="w-4 h-4" /> History
          </Button>

          <Button
            variant="ghost"
            size="sm"
            onClick={() => setShowRevise(!showRevise)}
            className={`gap-1 ${showRevise ? "text-primary" : ""}`}
          >
            <Bot className="w-4 h-4" /> Ask Bot to Revise
          </Button>

          <Dialog>
            <DialogTrigger asChild>
              <Button variant="ghost" size="sm" className="gap-1">
                <Download className="w-4 h-4" /> Export
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Export Document</DialogTitle>
              </DialogHeader>
              <div className="space-y-3">
                <Button
                  variant="outline"
                  className="w-full justify-start gap-2"
                  onClick={() => window.open(`${BASE}/api/documents/${docId}/export/html`, "_blank")}
                >
                  <FileText className="w-4 h-4" /> Export as HTML
                </Button>
                <Button
                  variant="outline"
                  className="w-full justify-start gap-2"
                  onClick={() => window.open(`${BASE}/api/documents/${docId}/export/docx`, "_blank")}
                >
                  <FileText className="w-4 h-4" /> Export as DOCX
                </Button>
              </div>
            </DialogContent>
          </Dialog>

          <Dialog>
            <DialogTrigger asChild>
              <Button variant="ghost" size="sm" className="gap-1">
                <Mail className="w-4 h-4" /> Email
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Email Document</DialogTitle>
              </DialogHeader>
              <div className="space-y-3">
                <Input
                  value={emailTo}
                  onChange={(e) => setEmailTo(e.target.value)}
                  placeholder="Recipient email"
                  type="email"
                />
                <Button
                  onClick={() => emailMutation.mutate(emailTo)}
                  disabled={!emailTo || emailMutation.isPending}
                  className="w-full gap-2"
                >
                  {emailMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
                  Send
                </Button>
              </div>
            </DialogContent>
          </Dialog>

          <Button
            variant="ghost"
            size="sm"
            onClick={() => notionMutation.mutate()}
            disabled={notionMutation.isPending}
            className="gap-1"
          >
            {notionMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <ExternalLink className="w-4 h-4" />}
            Notion
          </Button>

          <Button
            variant="ghost"
            size="sm"
            onClick={() => {
              if (confirm("Delete this document?")) deleteMutation.mutate();
            }}
            className="gap-1 text-destructive hover:text-destructive"
          >
            <Trash2 className="w-4 h-4" />
          </Button>

          <Button
            onClick={() => saveMutation.mutate()}
            disabled={!hasUnsavedChanges || saveMutation.isPending}
            className="gap-1"
          >
            {saveMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
            Save
          </Button>
        </div>
      </div>

      <Input
        value={editedTitle ?? doc.title}
        onChange={(e) => setEditedTitle(e.target.value)}
        className="text-xl font-display font-bold border-none bg-transparent px-0 focus-visible:ring-0"
        placeholder="Document title"
      />

      <div className="flex gap-4">
        <div className={`flex-1 ${showHistory || showRevise ? "max-w-[calc(100%-320px)]" : ""}`}>
          <RichTextEditor
            content={doc.content}
            onChange={(c) => setEditedContent(c)}
          />
        </div>

        {(showHistory || showRevise) && (
          <div className="w-[300px] shrink-0">
            <Card className="border-border/50 sticky top-24">
              <CardContent className="p-4 max-h-[calc(100vh-200px)] overflow-y-auto">
                {showRevise && (
                  <div className="space-y-3 mb-4">
                    <h3 className="text-sm font-tech text-muted-foreground uppercase tracking-wider">
                      Ask Bot to Revise
                    </h3>
                    <Textarea
                      value={reviseInstruction}
                      onChange={(e) => setReviseInstruction(e.target.value)}
                      placeholder="Describe how you'd like the document revised..."
                      rows={4}
                    />
                    <Button
                      onClick={() => reviseMutation.mutate(reviseInstruction)}
                      disabled={!reviseInstruction || reviseMutation.isPending}
                      className="w-full gap-2"
                    >
                      {reviseMutation.isPending ? (
                        <Loader2 className="w-4 h-4 animate-spin" />
                      ) : (
                        <Bot className="w-4 h-4" />
                      )}
                      Revise Document
                    </Button>
                    {showHistory && <div className="border-t border-border/30 pt-4" />}
                  </div>
                )}
                {showHistory && (
                  <VersionHistoryPanel
                    versions={doc.versionHistory}
                    onRestore={(v) => restoreMutation.mutate(v)}
                    isRestoring={restoreMutation.isPending}
                  />
                )}
              </CardContent>
            </Card>
          </div>
        )}
      </div>
    </div>
  );
}

export default function DocumentStudio() {
  const [selectedDocId, setSelectedDocId] = useState<number | null>(null);
  const queryClient = useQueryClient();
  const { toast } = useToast();

  const createMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(`${BASE}/api/documents`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: "Untitled Document",
          content: { type: "doc", content: [{ type: "paragraph" }] },
        }),
      });
      if (!res.ok) throw new Error("Failed to create document");
      return res.json();
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["documents"] });
      setSelectedDocId(data.id);
      toast({ title: "Document created" });
    },
  });

  return (
    <AppLayout>
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8 max-w-6xl">
        {selectedDocId ? (
          <DocumentEditor docId={selectedDocId} onBack={() => setSelectedDocId(null)} />
        ) : (
          <DocumentList
            onSelect={(id) => setSelectedDocId(id)}
            onCreate={() => createMutation.mutate()}
          />
        )}
      </div>
    </AppLayout>
  );
}
