import { Mail, Calendar, FileText, BarChart3, MessageSquare, Table2, Github, Twitter, Facebook, Instagram, Youtube, Music2, Share2, Truck } from "lucide-react";

export const SERVICES = [
  {
    key: "gmail",
    name: "Gmail",
    description: "Send and read emails on behalf of the client using Gmail API.",
    icon: Mail,
    oauthSupported: true,
    credentialLabel: "Gmail OAuth Access Token",
    credentialPlaceholder: "Paste your OAuth access token here...",
    helpUrl: "https://developers.google.com/gmail/api/auth/about-auth",
    helpText: "Go to Google Cloud Console → APIs → Credentials → OAuth 2.0 Client IDs",
  },
  {
    key: "google_calendar",
    name: "Google Calendar",
    description: "Create and list calendar events using Google Calendar API.",
    icon: Calendar,
    oauthSupported: true,
    credentialLabel: "Google Calendar OAuth Access Token",
    credentialPlaceholder: "Paste your OAuth access token here...",
    helpUrl: "https://developers.google.com/calendar/api/guides/auth",
    helpText: "Go to Google Cloud Console → APIs → Credentials → OAuth 2.0 Client IDs",
  },
  {
    key: "hubspot",
    name: "HubSpot",
    description: "Manage CRM contacts and deals using HubSpot private app token.",
    icon: BarChart3,
    oauthSupported: true,
    credentialLabel: "HubSpot Private App Access Token",
    credentialPlaceholder: "pat-na1-xxxx-xxxx-xxxx...",
    helpUrl: "https://developers.hubspot.com/docs/api/private-apps",
    helpText: "HubSpot → Settings → Integrations → Private Apps → Create a private app",
  },
  {
    key: "notion",
    name: "Notion",
    description: "Create and read documents/pages using Notion integration token.",
    icon: FileText,
    oauthSupported: true,
    credentialLabel: "Notion Integration Token",
    credentialPlaceholder: "ntn_xxxxxxxxxxxx...",
    helpUrl: "https://www.notion.so/my-integrations",
    helpText: "Notion → Settings → Integrations → Develop your own integrations → New integration",
  },
  {
    key: "slack",
    name: "Slack",
    description: "Post messages and notifications to Slack channels on behalf of your team.",
    icon: MessageSquare,
    oauthSupported: true,
    credentialLabel: "Slack Bot Token",
    credentialPlaceholder: "xoxb-xxxxxxxxxxxx...",
    helpUrl: "https://api.slack.com/apps",
    helpText: "Slack API → Your Apps → Create New App → OAuth & Permissions → Bot Token Scopes",
  },
  {
    key: "google_sheets",
    name: "Google Sheets",
    description: "Read and write rows in Google Sheets using the Sheets API.",
    icon: Table2,
    oauthSupported: false,
    credentialLabel: "Google Sheets Service Account JSON",
    credentialPlaceholder: '{"type":"service_account","project_id":"..."}',
    helpUrl: "https://developers.google.com/sheets/api/guides/authorizing",
    helpText: "Google Cloud Console → IAM → Service Accounts → Create → Download JSON key",
  },
  {
    key: "twilio",
    name: "Twilio SMS",
    description: "Send SMS messages via Twilio.",
    icon: MessageSquare,
    oauthSupported: false,
    credentialLabel: "Twilio Credentials (JSON)",
    credentialPlaceholder: '{"accountSid":"ACxxxxxxxxxx","authToken":"xxxxxxxx"}',
    helpUrl: "https://console.twilio.com/",
    helpText: "Twilio Console → Account → API Keys & Tokens. Copy Account SID and Auth Token.",
  },
  {
    key: "github",
    name: "GitHub",
    description: "Create issues and track engineering tasks in GitHub repositories.",
    icon: Github,
    oauthSupported: false,
    credentialLabel: "GitHub Personal Access Token",
    credentialPlaceholder: "ghp_xxxxxxxxxxxxxxxxxxxx...",
    helpUrl: "https://github.com/settings/tokens",
    helpText: "GitHub → Settings → Developer settings → Personal access tokens → Generate new token",
  },
  {
    key: "twitter",
    name: "Twitter / X",
    description: "Post tweets and social content using the Twitter API v2.",
    icon: Twitter,
    oauthSupported: false,
    credentialLabel: "Twitter Bearer Token",
    credentialPlaceholder: "AAAA...",
    helpUrl: "https://developer.twitter.com/en/portal/dashboard",
    helpText: "Twitter Developer Portal → Projects & Apps → Your App → Keys and tokens → Bearer Token",
  },
  {
    key: "facebook",
    name: "Facebook",
    description: "Post content and manage your Facebook Page using the Graph API.",
    icon: Facebook,
    oauthSupported: false,
    credentialLabel: "Facebook Page Access Token",
    credentialPlaceholder: "EAAxxxxxxxxxxxx...",
    helpUrl: "https://developers.facebook.com/tools/explorer/",
    helpText: "Facebook Graph API Explorer → select your app → Generate Access Token → grant pages_manage_posts and pages_read_engagement permissions",
  },
  {
    key: "instagram",
    name: "Instagram",
    description: "Publish posts and manage content on your Instagram Business account via the Graph API.",
    icon: Instagram,
    oauthSupported: false,
    credentialLabel: "Instagram Access Token",
    credentialPlaceholder: "EAAxxxxxxxxxxxx...",
    helpUrl: "https://developers.facebook.com/docs/instagram-api/getting-started",
    helpText: "Facebook Developer Console → Your App → Instagram Graph API → generate a long-lived token with instagram_basic and instagram_content_publish permissions",
  },
  {
    key: "youtube",
    name: "YouTube",
    description: "Upload videos, manage your channel, and schedule content using the YouTube Data API.",
    icon: Youtube,
    oauthSupported: false,
    credentialLabel: "YouTube OAuth Refresh Token (JSON)",
    credentialPlaceholder: '{"client_id":"...","client_secret":"...","refresh_token":"..."}',
    helpUrl: "https://developers.google.com/youtube/v3/guides/auth/server-side-web-apps",
    helpText: "Google Cloud Console → APIs → YouTube Data API v3 → Credentials → OAuth 2.0 → Download JSON, then exchange for a refresh token",
  },
  {
    key: "tiktok",
    name: "TikTok",
    description: "Publish videos and manage content on your TikTok Business account using the TikTok API.",
    icon: Music2,
    oauthSupported: false,
    credentialLabel: "TikTok Access Token",
    credentialPlaceholder: "act.xxxxxxxxxxxx...",
    helpUrl: "https://developers.tiktok.com/doc/overview",
    helpText: "TikTok for Developers → Manage Apps → Your App → Keys & Access → generate an access token with video.publish and video.list scopes",
  },
  {
    key: "social365",
    name: "Social365.ai",
    description: "Schedule and publish AI-generated content across all your social channels via Social365.ai.",
    icon: Share2,
    oauthSupported: false,
    credentialLabel: "Social365.ai API Key",
    credentialPlaceholder: "s365_xxxxxxxxxxxx...",
    helpUrl: "https://social365.ai",
    helpText: "Social365.ai → Account Settings → API → Generate API Key",
  },
  {
    key: "family_movers_crm",
    name: "Family Movers CRM",
    description: "Connect to the Family Movers proprietary CRM to sync leads, bookings, and customer records.",
    icon: Truck,
    oauthSupported: false,
    credentialLabel: "Family Movers CRM API Key",
    credentialPlaceholder: "fm_xxxxxxxxxxxx...",
    helpUrl: "https://familymovers.ca",
    helpText: "Family Movers CRM → Settings → API Access → Generate API Key",
  },
];
