/**
 * Content & Data assets engine (task #265).
 *
 * Shared service that powers the "Content & Data Creator" bot and the scheduled
 * newsletter job. It produces three kinds of income-oriented assets and stores
 * each as an Asset Studio asset so it flows through the existing human review
 * gate before publishing/export:
 *
 *   - blog      : programmatic-SEO articles (reviews / comparisons / guides)
 *   - newsletter: recurring industry/tech digest issues
 *   - dataset   : a curated, cleaned dataset/report packaged as a downloadable file
 *
 * Generation goes through `callWithFallback` (the single safe execution path:
 * circuit breakers, fallback chains, usage logging, governance downstream) and
 * brand-voice guardrails, never a raw provider call. Nothing is published or
 * exported here — assets land in `draft` (or `in_review`) and a human approves.
 */

import {
  db,
  assetsTable,
  assetFilesTable,
  type AssetStatus,
  type AssetStatusEvent,
} from "@workspace/db";
import { eq, and } from "drizzle-orm";
import { callWithFallback, ModelTier } from "../ai-safety/model-fallback";
import { applyBrandVoiceGuardrails } from "../platform/governance";
import { ObjectStorageService } from "../../lib/objectStorage";

const objectStorage = new ObjectStorageService();

export type ContentKind = "blog" | "newsletter" | "dataset";
export type ArticleFormat = "review" | "comparison" | "guide";

function appendStatus(
  history: AssetStatusEvent[] | null | undefined,
  status: AssetStatus,
  changedBy: string,
  note?: string,
): AssetStatusEvent[] {
  return [
    ...(history ?? []),
    { status, changedBy, note, at: new Date().toISOString() },
  ];
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80);
}

function firstHeading(markdown: string, fallback: string): string {
  const m = markdown.match(/^#\s+(.+)$/m) || markdown.match(/^(.+?)\n/);
  return m ? m[1].replace(/^#+\s*/, "").trim() : fallback;
}

function plainExcerpt(markdown: string, max = 200): string {
  const text = markdown
    .replace(/^#+\s*/gm, "")
    .replace(/[*_`>#-]/g, "")
    .replace(/\s+/g, " ")
    .trim();
  return text.length > max ? text.slice(0, max).trimEnd() + "…" : text;
}

async function generateMarkdown(params: {
  systemPrompt: string;
  userPrompt: string;
  clientId?: number;
  botId?: number;
  maxTokens?: number;
  tier?: ModelTier;
}): Promise<string> {
  const result = await callWithFallback({
    model: "gpt-5-mini",
    preferredTier: params.tier ?? ModelTier.EFFICIENT,
    maxCompletionTokens: params.maxTokens ?? 3000,
    clientId: params.clientId,
    botId: params.botId,
    messages: [
      { role: "system", content: params.systemPrompt },
      { role: "user", content: params.userPrompt },
    ],
  });
  const content = result.completion.choices[0]?.message?.content;
  return typeof content === "string" ? content.trim() : "";
}

/**
 * Upload a generated buffer to object storage from the server side and return
 * the normalized entity path (suitable for asset_files.objectPath). Uses the
 * same signed-PUT flow the browser upload path uses, just executed in-process.
 */
async function uploadBuffer(
  clientId: number,
  body: Buffer | string,
  contentType: string,
): Promise<string> {
  const uploadUrl = await objectStorage.getObjectEntityUploadURL(`client-${clientId}`);
  const resp = await fetch(uploadUrl, {
    method: "PUT",
    headers: { "Content-Type": contentType },
    body,
    signal: AbortSignal.timeout(30_000),
  });
  if (!resp.ok) {
    throw new Error(`Object upload failed: HTTP ${resp.status}`);
  }
  return objectStorage.normalizeObjectEntityPath(uploadUrl.split("?")[0]);
}

interface CreateAssetParams {
  clientId: number;
  botId?: number | null;
  botName?: string;
  title: string;
  type: string;
  description?: string;
  niche?: string;
  targetPlatform?: string;
  metadata: Record<string, unknown>;
  submitForReview?: boolean;
}

async function createContentAsset(params: CreateAssetParams) {
  const changedBy = `bot:${params.botName ?? params.botId ?? "content-data-creator"}`;
  const status: AssetStatus = params.submitForReview ? "in_review" : "draft";
  const history = appendStatus(
    appendStatus([], "draft", changedBy, "generated by Content & Data Creator"),
    status,
    changedBy,
    params.submitForReview ? "submitted for review" : undefined,
  );

  const [asset] = await db
    .insert(assetsTable)
    .values({
      clientId: params.clientId,
      botId: params.botId ?? null,
      title: params.title,
      type: params.type,
      description: params.description ?? null,
      niche: params.niche ?? null,
      targetPlatform: params.targetPlatform ?? null,
      status,
      metadata: params.metadata,
      statusHistory: status === "in_review" ? history : appendStatus([], "draft", changedBy, "generated by Content & Data Creator"),
    })
    .returning();
  return asset;
}

// ── Programmatic-SEO blog article ───────────────────────────────────────────
export interface GenerateArticleParams {
  clientId: number;
  botId?: number | null;
  botName?: string;
  topic: string;
  targetKeyword: string;
  format?: ArticleFormat;
  niche?: string;
  author?: string;
  category?: string;
  secondaryKeywords?: string[];
  submitForReview?: boolean;
}

export async function generateSeoArticleAsset(params: GenerateArticleParams) {
  const format = params.format ?? "guide";
  const formatBrief: Record<ArticleFormat, string> = {
    review: "an in-depth, balanced product/service review with pros, cons, who it's for, and a verdict",
    comparison: "a head-to-head comparison covering key dimensions in a structured way, with a recommendation per use-case",
    guide: "a comprehensive, well-structured how-to / niche guide that fully answers the search intent",
  };

  const systemPrompt = `You are an expert programmatic-SEO content writer. Write ${formatBrief[format]}.
Requirements:
- Start with a single H1 title (\`# ...\`) that naturally includes the target keyword.
- Use clear H2/H3 subheadings, short paragraphs, and bullet lists where helpful.
- Optimize for search intent and answer-engine extraction (FAQ-style sections, definitions, comparisons).
- Naturally include the target keyword and secondary keywords; never keyword-stuff.
- End with a concise conclusion and a short FAQ section.
Return GitHub-flavored markdown only — no preamble, no code fences around the whole document.`;

  const userPrompt = `Topic: ${params.topic}
Target keyword: ${params.targetKeyword}
${params.secondaryKeywords?.length ? `Secondary keywords: ${params.secondaryKeywords.join(", ")}\n` : ""}${params.niche ? `Niche/audience: ${params.niche}\n` : ""}Article format: ${format}

Write the full article now.`;

  let markdown = await generateMarkdown({
    systemPrompt,
    userPrompt,
    clientId: params.clientId,
    botId: params.botId ?? undefined,
    maxTokens: 3500,
  });
  if (!markdown) throw new Error("Article generation returned no content");

  markdown = await applyBrandVoiceGuardrails(params.clientId, markdown);

  const title = firstHeading(markdown, params.topic);
  const slug = slugify(title) || slugify(params.targetKeyword);
  const excerpt = plainExcerpt(markdown);
  const author = params.author ?? "GalaxyBots";
  const category = params.category ?? "Insights";

  const asset = await createContentAsset({
    clientId: params.clientId,
    botId: params.botId,
    botName: params.botName,
    title,
    type: "other",
    description: `Programmatic-SEO ${format} targeting "${params.targetKeyword}".`,
    niche: params.niche,
    targetPlatform: "Blog",
    submitForReview: params.submitForReview,
    metadata: {
      contentKind: "blog" satisfies ContentKind,
      content: markdown,
      slug,
      excerpt,
      author,
      category,
      targetKeyword: params.targetKeyword,
      secondaryKeywords: params.secondaryKeywords ?? [],
      articleFormat: format,
      wordCount: markdown.split(/\s+/).length,
    },
  });

  return { asset, title, slug, wordCount: markdown.split(/\s+/).length };
}

// ── Recurring newsletter issue ──────────────────────────────────────────────
export interface GenerateNewsletterParams {
  clientId: number;
  botId?: number | null;
  botName?: string;
  industry: string;
  audience?: string;
  tone?: string;
  focus?: string;
  edition?: string;
  submitForReview?: boolean;
}

export async function generateNewsletterAsset(params: GenerateNewsletterParams) {
  const edition =
    params.edition ??
    new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" });

  const systemPrompt = `You are the editor of a respected industry/tech newsletter. Write a single newsletter issue as markdown.
Structure:
- An H1 issue title (\`# ...\`) and a one-line edition subtitle.
- A short editor's intro (2-3 sentences).
- 3-5 digest sections with H2 headings: a notable trend/story, a "why it matters", and a quick takeaway each.
- A short "Tools & resources" list and a one-line sign-off.
Keep it skimmable and useful. Return markdown only.`;

  const userPrompt = `Industry: ${params.industry}
${params.audience ? `Audience: ${params.audience}\n` : ""}${params.focus ? `This issue's focus: ${params.focus}\n` : ""}Edition: ${edition}
Tone: ${params.tone ?? "professional, insightful, concise"}

Write the newsletter issue now.`;

  let markdown = await generateMarkdown({
    systemPrompt,
    userPrompt,
    clientId: params.clientId,
    botId: params.botId ?? undefined,
    maxTokens: 3000,
  });
  if (!markdown) throw new Error("Newsletter generation returned no content");

  markdown = await applyBrandVoiceGuardrails(params.clientId, markdown);

  const title = firstHeading(markdown, `${params.industry} Digest — ${edition}`);
  const excerpt = plainExcerpt(markdown);

  const asset = await createContentAsset({
    clientId: params.clientId,
    botId: params.botId,
    botName: params.botName,
    title,
    type: "other",
    description: `Newsletter issue (${edition}) for the ${params.industry} industry.`,
    niche: params.industry,
    targetPlatform: "Newsletter (export)",
    submitForReview: params.submitForReview,
    metadata: {
      contentKind: "newsletter" satisfies ContentKind,
      content: markdown,
      excerpt,
      industry: params.industry,
      edition,
      tone: params.tone ?? "professional",
    },
  });

  // Export deliverable: attach the issue as a downloadable markdown file.
  try {
    const objectPath = await uploadBuffer(params.clientId, markdown, "text/markdown");
    await db.insert(assetFilesTable).values({
      assetId: asset.id,
      clientId: params.clientId,
      kind: "other",
      fileName: `${slugify(title) || "newsletter"}-${slugify(edition)}.md`,
      objectPath,
      contentType: "text/markdown",
      sizeBytes: Buffer.byteLength(markdown),
    });
  } catch (err) {
    console.warn("[ContentAssets] newsletter file attach failed (non-fatal):", err instanceof Error ? err.message : err);
  }

  return { asset, title, edition };
}

// ── Curated dataset / trend report ──────────────────────────────────────────
export interface DatasetSource {
  url: string;
  title?: string;
  content: string;
}

export interface AssembleDatasetParams {
  clientId: number;
  botId?: number | null;
  botName?: string;
  industry: string;
  topic: string;
  sources: DatasetSource[];
  columns?: string[];
  format?: "csv" | "json";
  submitForReview?: boolean;
}

interface DatasetResult {
  columns: string[];
  rows: Array<Record<string, string>>;
  summary: string;
}

function toCsv(columns: string[], rows: Array<Record<string, string>>): string {
  const esc = (v: string) => {
    const s = String(v ?? "");
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const header = columns.map(esc).join(",");
  const body = rows
    .map((row) => columns.map((c) => esc(row[c] ?? "")).join(","))
    .join("\n");
  return `${header}\n${body}\n`;
}

export async function assembleDatasetAsset(params: AssembleDatasetParams) {
  if (!params.sources.length) {
    throw new Error("At least one source is required to assemble a dataset");
  }
  const format = params.format ?? "csv";

  const sourcesBlock = params.sources
    .map((s, i) => `SOURCE ${i + 1} (${s.title ?? s.url}):\n${s.content.slice(0, 4000)}`)
    .join("\n\n---\n\n");

  const systemPrompt = `You are a data analyst building a clean, curated dataset/trend report from raw scraped sources.
Read the sources and extract a structured, deduplicated dataset.
${params.columns?.length ? `Use exactly these columns: ${params.columns.join(", ")}.` : "Choose 4-7 clear, consistent columns appropriate to the topic."}
Clean the data: trim whitespace, normalize casing/units, drop empty or duplicate rows, and only include facts actually supported by the sources.
Respond with STRICT JSON only, shaped as:
{"columns": string[], "rows": Array<object keyed by column>, "summary": string}
No markdown, no commentary — JSON only.`;

  const userPrompt = `Industry: ${params.industry}
Topic: ${params.topic}

Raw sources:
${sourcesBlock}

Produce the cleaned dataset JSON now.`;

  const raw = await generateMarkdown({
    systemPrompt,
    userPrompt,
    clientId: params.clientId,
    botId: params.botId ?? undefined,
    maxTokens: 4000,
  });

  let parsed: DatasetResult;
  try {
    const jsonText = raw.replace(/^```(?:json)?\s*/i, "").replace(/```\s*$/i, "").trim();
    parsed = JSON.parse(jsonText) as DatasetResult;
  } catch {
    throw new Error("Dataset analysis did not return valid JSON");
  }
  const columns = Array.isArray(parsed.columns) && parsed.columns.length ? parsed.columns : params.columns ?? [];
  const rows = Array.isArray(parsed.rows) ? parsed.rows : [];
  if (!columns.length || !rows.length) {
    throw new Error("Dataset analysis produced no usable rows");
  }

  const fileBody = format === "json" ? JSON.stringify(rows, null, 2) : toCsv(columns, rows);
  const contentType = format === "json" ? "application/json" : "text/csv";
  const title = `${params.topic} — ${params.industry} dataset`;

  const asset = await createContentAsset({
    clientId: params.clientId,
    botId: params.botId,
    botName: params.botName,
    title,
    type: "data",
    description: `Curated ${format.toUpperCase()} dataset on "${params.topic}" assembled and cleaned from ${params.sources.length} source(s).`,
    niche: params.industry,
    targetPlatform: "Dataset / report (export)",
    submitForReview: params.submitForReview,
    metadata: {
      contentKind: "dataset" satisfies ContentKind,
      summary: parsed.summary ?? "",
      columns,
      rowCount: rows.length,
      format,
      sourceUrls: params.sources.map((s) => s.url),
    },
  });

  const objectPath = await uploadBuffer(params.clientId, fileBody, contentType);
  const [file] = await db
    .insert(assetFilesTable)
    .values({
      assetId: asset.id,
      clientId: params.clientId,
      kind: "dataset",
      fileName: `${slugify(params.topic) || "dataset"}.${format}`,
      objectPath,
      contentType,
      sizeBytes: Buffer.byteLength(fileBody),
    })
    .returning();

  return { asset, fileId: file.id, rowCount: rows.length, columns };
}

/**
 * Load a published blog-kind asset's content and mirror it into the public
 * blog surface (blog_posts). Idempotent on slug. Called when a human approves
 * and publishes a blog asset.
 */
export async function publishBlogAssetToBlogSurface(assetId: number, clientId: number) {
  const { blogPostsTable } = await import("@workspace/db");
  const [asset] = await db
    .select()
    .from(assetsTable)
    .where(and(eq(assetsTable.id, assetId), eq(assetsTable.clientId, clientId)));
  if (!asset) return null;
  const meta = (asset.metadata ?? {}) as Record<string, unknown>;
  if (meta.contentKind !== "blog" || typeof meta.content !== "string") return null;

  const slug = (typeof meta.slug === "string" && meta.slug) || slugify(asset.title);
  const [existing] = await db
    .select({ id: blogPostsTable.id })
    .from(blogPostsTable)
    .where(eq(blogPostsTable.slug, slug))
    .limit(1);
  if (existing) return { slug, alreadyPublished: true };

  await db.insert(blogPostsTable).values({
    title: asset.title,
    slug,
    excerpt: (typeof meta.excerpt === "string" && meta.excerpt) || plainExcerpt(meta.content),
    content: meta.content,
    author: (typeof meta.author === "string" && meta.author) || "GalaxyBots",
    category: (typeof meta.category === "string" && meta.category) || "Insights",
  });
  return { slug, alreadyPublished: false };
}
