import { db, missionPlaybooksTable } from "@workspace/db";
import { eq, and } from "drizzle-orm";

type PlaybookStep = { order: number; role: string; objective: string };
type PlaybookSeed = { name: string; description: string; category: string; isBuiltIn: true; steps: PlaybookStep[] };

function steps(...roles: [string, string][]): PlaybookStep[] {
  return roles.map(([role, objective], i) => ({ order: i + 1, role, objective }));
}

const BUILT_IN_PLAYBOOKS: PlaybookSeed[] = [
  // ─── FORTUNE 50 (1–20) ───────────────────────────────────────────────────
  { name: "Quarterly Strategy War Room", description: "Compress 6 weeks of strategic planning into 5 days using parallel AI Director analysis and virtual boardroom debate.", category: "fortune50", isBuiltIn: true, steps: steps(["Chairman Atlas", "Cross-functional facilitation"], ["CFO Sentinel Marcus", "Financial modeling"], ["FP&A Oracle Demi", "Scenario analysis"], ["Risk Warden Okafor", "Threat assessment"]) },
  { name: "M&A Target Scoring Engine", description: "Evaluate 100+ acquisition targets simultaneously with consistent criteria and 24-hour turnaround.", category: "fortune50", isBuiltIn: true, steps: steps(["FP&A Oracle Demi", "Parallel valuation modeling"], ["General Counsel Alexis", "Regulatory risk flagging"], ["Tech Visionary Zara", "Tech stack assessment"], ["Growth Hawk Yusuf", "Market expansion potential"]) },
  { name: "Regulatory Response Accelerator", description: "Respond to regulatory inquiries within hours using AI-drafted responses and legal review.", category: "fortune50", isBuiltIn: true, steps: steps(["General Counsel Alexis", "Lead regulatory response"], ["CISO Sentinel Nova", "Data security analysis"], ["Risk Warden Okafor", "Exposure assessment"]) },
  { name: "Supply Chain Disruption War Room", description: "Respond to supply chain disruptions in real-time with AI-modeled alternatives and immediate action plans.", category: "fortune50", isBuiltIn: true, steps: steps(["Operator Rex", "Operations monitoring"], ["CFO Sentinel Marcus", "Cost impact analysis"], ["Risk Warden Okafor", "Cascading risk mapping"]) },
  { name: "Competitive Intelligence Mesh", description: "Maintain continuous, real-time intelligence on all competitors across all markets.", category: "fortune50", isBuiltIn: true, steps: steps(["Growth Hawk Yusuf", "Market move tracking"], ["Brand Maven Priya", "Positioning shift analysis"], ["Product Oracle Sasha", "Product change detection"]) },
  { name: "Investor Relations Insight Engine", description: "Prepare for earnings calls and analyst meetings by predicting every likely question before it is asked.", category: "fortune50", isBuiltIn: true, steps: steps(["CFO Sentinel Marcus", "Financial narrative"], ["FP&A Oracle Demi", "Guidance modeling"], ["Closer King Rivera", "Analyst psychology"]) },
  { name: "Product Launch Battle Simulator", description: "War-game product launches against likely competitive responses before committing resources.", category: "fortune50", isBuiltIn: true, steps: steps(["Product Oracle Sasha", "Launch plan definition"], ["Growth Hawk Yusuf", "Competitor role-play"], ["CFO Sentinel Marcus", "Financial impact modeling"], ["Brand Maven Priya", "Positioning defense"]) },
  { name: "Talent Succession Risk Monitor", description: "Identify and mitigate leadership gaps before they become crises with continuous risk scoring.", category: "fortune50", isBuiltIn: true, steps: steps(["HR Director Amara", "Succession analysis"], ["Operator Rex", "Process continuity planning"], ["FP&A Oracle Demi", "Replacement cost modeling"]) },
  { name: "Pricing Optimization Engine", description: "Run dynamic, market-responsive pricing across thousands of SKUs with overnight scenario modeling.", category: "fortune50", isBuiltIn: true, steps: steps(["CFO Sentinel Marcus", "Margin impact analysis"], ["Growth Hawk Yusuf", "Volume trade-off modeling"]) },
  { name: "Annual Planning Compressor", description: "Complete annual planning in 4 weeks instead of 4 months with AI-drafted departmental plans.", category: "fortune50", isBuiltIn: true, steps: steps(["FP&A Oracle Demi", "Resource allocation"], ["Operator Rex", "Operational plan drafting"], ["Chairman Atlas", "Cross-functional alignment"]) },
  { name: "Crisis Communication Commander", description: "Respond to PR crises within hours with coordinated, legally vetted messaging across all channels.", category: "fortune50", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Message drafting"], ["General Counsel Alexis", "Legal review"], ["Risk Warden Okafor", "Escalation scenarios"], ["Closer King Rivera", "Stakeholder management"]) },
  { name: "Board Meeting Pre-Flight", description: "Predict every board question and have data-backed answers ready before the meeting starts.", category: "fortune50", isBuiltIn: true, steps: steps(["Chairman Atlas", "Board psychology analysis"], ["CFO Sentinel Marcus", "Financial question prep"], ["General Counsel Alexis", "Governance questions"], ["FP&A Oracle Demi", "Forward-looking statements"]) },
  { name: "Innovation Funnel Accelerator", description: "Screen 1,000+ ideas to identify the top 10 in 30 days using 9 AI scoring filters.", category: "fortune50", isBuiltIn: true, steps: steps(["Product Oracle Sasha", "Feasibility assessment"], ["Tech Visionary Zara", "Technical path analysis"], ["CFO Sentinel Marcus", "ROI evaluation"], ["Risk Warden Okafor", "Failure scenario modeling"]) },
  { name: "Customer Churn Prevention Unit", description: "Identify at-risk customers 90 days before they leave and deploy tailored intervention playbooks.", category: "fortune50", isBuiltIn: true, steps: steps(["Closer King Rivera", "Retention strategy"], ["Product Oracle Sasha", "Feature alignment"], ["FP&A Oracle Demi", "Revenue impact modeling"]) },
  { name: "Merger Integration Orchestrator", description: "Execute Day 1 integration across 50+ workstreams simultaneously with AI-tracked progress.", category: "fortune50", isBuiltIn: true, steps: steps(["Operator Rex", "Workstream coordination"], ["HR Director Amara", "Cultural integration"], ["Tech Visionary Zara", "Systems integration"], ["General Counsel Alexis", "Legal entity consolidation"]) },
  { name: "Regulatory Horizon Scanner", description: "Anticipate regulatory changes 12-24 months in advance and build proactive response strategies.", category: "fortune50", isBuiltIn: true, steps: steps(["General Counsel Alexis", "Regulatory mapping"], ["Risk Warden Okafor", "Impact assessment"]) },
  { name: "Workforce Productivity Navigator", description: "Identify productivity bottlenecks and optimization opportunities across large employee populations.", category: "fortune50", isBuiltIn: true, steps: steps(["Operator Rex", "Process optimization"], ["HR Director Amara", "Workforce analytics"], ["Tech Visionary Zara", "Tool efficiency analysis"]) },
  { name: "Earnings Call Defense System", description: "Prepare for every possible earnings call question by training against 200+ scenarios and 10 analyst personas.", category: "fortune50", isBuiltIn: true, steps: steps(["CFO Sentinel Marcus", "Financial question prep"], ["Closer King Rivera", "Analyst psychology"], ["Brand Maven Priya", "Message discipline"]) },
  { name: "Strategic Partnership Evaluator", description: "Assess 50+ partnership opportunities simultaneously using consistent weighted scoring criteria.", category: "fortune50", isBuiltIn: true, steps: steps(["Growth Hawk Yusuf", "Strategic fit scoring"], ["CFO Sentinel Marcus", "Financial modeling"], ["General Counsel Alexis", "Agreement terms"], ["Risk Warden Okafor", "Dependency risk"]) },
  { name: "ESG Intelligence Core", description: "Real-time ESG monitoring, reporting, and improvement recommendations across all regulatory frameworks.", category: "fortune50", isBuiltIn: true, steps: steps(["Risk Warden Okafor", "Reputation risk monitoring"], ["General Counsel Alexis", "Compliance tracking"], ["Brand Maven Priya", "Stakeholder communication"]) },

  // ─── CEO / ENTERPRISE STRATEGY (21–35) ───────────────────────────────────
  { name: "Corporate Narrative Weaving", description: "Maintain a consistent, compelling corporate story across all channels and stakeholders with weekly narrative health scoring.", category: "ceo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Messaging consistency audit"], ["Chairman Atlas", "Narrative framework"], ["Magnus Drake", "Channel adaptation strategy"]) },
  { name: "Board Dynamics Optimizer", description: "Improve board effectiveness by analyzing interaction patterns, voting trends, and decision quality.", category: "ceo", isBuiltIn: true, steps: steps(["Chairman Atlas", "Board interaction analysis"], ["HR Director Amara", "Director participation equity"], ["Risk Warden Okafor", "Groupthink detection"]) },
  { name: "Stakeholder Sentiment Mesh", description: "Real-time sentiment analysis across six stakeholder categories — customers, employees, investors, regulators, media, NGOs.", category: "ceo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Sentiment monitoring"], ["Risk Warden Okafor", "Early warning alerts"], ["Closer King Rivera", "Relationship management"]) },
  { name: "CEO Time Allocation Optimizer", description: "Optimize CEO time for maximum enterprise value by auditing calendar and decision logs against value creation metrics.", category: "ceo", isBuiltIn: true, steps: steps(["Operator Rex", "Calendar analysis"], ["FP&A Oracle Demi", "Value creation mapping"], ["Magnus Drake", "Delegation strategy"]) },
  { name: "Culture Health Diagnostic", description: "Quantify and improve organizational culture with a monthly Culture Health Index tracking psychological safety, innovation, and execution.", category: "ceo", isBuiltIn: true, steps: steps(["HR Director Amara", "Culture data analysis"], ["Operator Rex", "Execution rigor scoring"], ["Brand Maven Priya", "Internal communication health"]) },
  { name: "Strategic Bet Portfolio Manager", description: "Manage strategic initiatives like a financial portfolio — with risk-adjusted ROI, success probability, and quarterly rebalancing.", category: "ceo", isBuiltIn: true, steps: steps(["FP&A Oracle Demi", "Portfolio ROI modeling"], ["CFO Sentinel Marcus", "Capital allocation"], ["Risk Warden Okafor", "Bet risk assessment"]) },
  { name: "Foresight-Driven Strategy Forums", description: "Embed strategic foresight into quarterly planning using scenario scanning and future stress-testing.", category: "ceo", isBuiltIn: true, steps: steps(["Chairman Atlas", "Scenario facilitation"], ["Magnus Drake", "Global trend analysis"], ["Risk Warden Okafor", "Strategy stress-testing"]) },
  { name: "Algorithmic State Readiness", description: "Prepare for AI-driven governance and regulatory shifts using the Algorithmic State framework.", category: "ceo", isBuiltIn: true, steps: steps(["General Counsel Alexis", "Regulatory landscape mapping"], ["Tech Visionary Zara", "AI governance assessment"]) },
  { name: "AI Strategy Roadmap", description: "Build a responsible, scalable AI strategy using a four-step framework: vision, maturity, use case prioritization, execution roadmap.", category: "ceo", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "AI maturity assessment"], ["Product Oracle Sasha", "Use case prioritization"], ["CISO Sentinel Nova", "Governance and risk"]) },
  { name: "Domain-Specific Model Strategy", description: "Deploy specialized AI models for competitive advantage in high-value domains.", category: "ceo", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Domain model selection"], ["Product Oracle Sasha", "Use case mapping"], ["CISO Sentinel Nova", "Security and compliance"]) },
  { name: "Geopatriation Risk Management", description: "Navigate shifting geopolitical tech landscape by mapping sovereign AI requirements and vendor geography risks.", category: "ceo", isBuiltIn: true, steps: steps(["General Counsel Alexis", "Sovereign compliance mapping"], ["CISO Sentinel Nova", "Vendor geography risk"], ["Tech Visionary Zara", "Infrastructure strategy"]) },
  { name: "Sovereign AI Capability Building", description: "Develop independent AI capabilities aligned with comparative advantage — without isolation.", category: "ceo", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "AI capability inventory"], ["General Counsel Alexis", "Standards and procurement"]) },
  { name: "CEO Shadow AI Detection & Integration", description: "Detect unauthorized AI usage across the organization and convert successful shadow workflows into compliant enterprise capabilities.", category: "ceo", isBuiltIn: true, steps: steps(["CISO Sentinel Nova", "Shadow AI observability"], ["Tech Visionary Zara", "Workflow conversion"], ["Operator Rex", "Enterprise integration"]) },
  { name: "Multiagent System Orchestration", description: "Deploy collaborative AI agents that handle routine tasks autonomously while humans focus on exceptions.", category: "ceo", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Agent architecture design"], ["Operator Rex", "Workflow automation"], ["Product Oracle Sasha", "Use case selection"]) },
  { name: "CEO Accountability for AI Outcomes", description: "Tie executive compensation to AI performance metrics — ensuring aligned incentives for AI value creation.", category: "ceo", isBuiltIn: true, steps: steps(["Chairman Atlas", "Governance framework"], ["CFO Sentinel Marcus", "Compensation modeling"], ["FP&A Oracle Demi", "AI ROI tracking"]) },

  // ─── CFO / FINANCE (36–50) ────────────────────────────────────────────────
  { name: "Risk-Adjusted ROI Framework", description: "Calculate true AI ROI by mapping the complete value chain and adjusting for hallucination rates, guardrail interventions, and model drift.", category: "cfo", isBuiltIn: true, steps: steps(["CFO Sentinel Marcus", "ROI framework design"], ["FP&A Oracle Demi", "Value chain mapping"], ["Risk Warden Okafor", "Risk adjustment modeling"]) },
  { name: "TCO-Based AI Budgeting", description: "Capture total cost of AI ownership across development and operations — including inference, labeling, monitoring, and human oversight.", category: "cfo", isBuiltIn: true, steps: steps(["CFO Sentinel Marcus", "TCO framework"], ["FP&A Oracle Demi", "Operational cost forecasting"], ["Tech Visionary Zara", "Infrastructure cost analysis"]) },
  { name: "Outcome-Based Pricing Negotiation", description: "Shift AI vendor contracts from license fees to outcome-based payments aligned with actual delivered value.", category: "cfo", isBuiltIn: true, steps: steps(["CFO Sentinel Marcus", "Contract restructuring"], ["General Counsel Alexis", "Legal terms"], ["Closer King Rivera", "Negotiation strategy"]) },
  { name: "AI Value Capture Attribution", description: "Isolate AI contribution from other initiatives using tagging frameworks to distinguish machine-generated, human-verified, and human-enhanced outputs.", category: "cfo", isBuiltIn: true, steps: steps(["FP&A Oracle Demi", "Attribution modeling"], ["Tech Visionary Zara", "Tagging framework setup"], ["Product Oracle Sasha", "Workflow phase tracking"]) },
  { name: "Productivity Leak Quantification", description: "Measure actual vs. theoretical productivity gains — identify and close leakage between promised and realized AI value.", category: "cfo", isBuiltIn: true, steps: steps(["FP&A Oracle Demi", "Leakage measurement"], ["Operator Rex", "Process auditing"], ["HR Director Amara", "Workforce utilization"]) },
  { name: "Generative Engine Optimization ROI", description: "Measure the financial value of being cited by AI engines as search volume shifts from traditional to generative platforms.", category: "cfo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Citation tracking"], ["FP&A Oracle Demi", "GEO ROI modeling"]) },
  { name: "R&D Tax Credit Capture for AI", description: "Claim tax credits for qualifying AI development activities including custom model development and multiagent orchestration.", category: "cfo", isBuiltIn: true, steps: steps(["CFO Sentinel Marcus", "Credit eligibility audit"], ["Tech Visionary Zara", "Technical documentation"], ["General Counsel Alexis", "Audit defense preparation"]) },
  { name: "Tariff Impact Modeling for Tech Spend", description: "Navigate hardware cost volatility from trade policy by modeling scenarios and building procurement buffers.", category: "cfo", isBuiltIn: true, steps: steps(["CFO Sentinel Marcus", "Tariff scenario modeling"], ["Operator Rex", "Alternative sourcing"], ["Risk Warden Okafor", "Trade risk assessment"]) },
  { name: "Value-Realization Speed Tracking", description: "Measure how quickly AI benefits materialize — set 90-day targets and track quick-win conversion rates.", category: "cfo", isBuiltIn: true, steps: steps(["FP&A Oracle Demi", "Value-realization timeline"], ["Product Oracle Sasha", "Quick win identification"], ["Closer King Rivera", "Benefit communication"]) },
  { name: "AI Portfolio Rebalancing", description: "Shift AI investment from peripheral tasks to high-value core operations — targeting an 80/20 core-to-periphery ratio.", category: "cfo", isBuiltIn: true, steps: steps(["CFO Sentinel Marcus", "Portfolio audit"], ["FP&A Oracle Demi", "ROI by domain"], ["Tech Visionary Zara", "Capability reallocation"]) },
  { name: "Agentic AI ROI Framework", description: "Measure value from autonomous systems by tracking task completion rate, human intervention frequency, and decision quality.", category: "cfo", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Agent performance metrics"], ["Operator Rex", "Autonomy rate tracking"], ["FP&A Oracle Demi", "ROI calculation"]) },
  { name: "Financial Sentiment Integration", description: "Incorporate market signals — analyst reports, investor calls, macro indicators — into dynamic financial forecasting.", category: "cfo", isBuiltIn: true, steps: steps(["CFO Sentinel Marcus", "Forecast updating"], ["FP&A Oracle Demi", "Sentiment modeling"], ["Brand Maven Priya", "Market signal scanning"]) },
  { name: "Dynamic Capital Allocation", description: "Shift capital to highest-ROI AI initiatives in real-time through quarterly reallocation and early sunsetting of underperformers.", category: "cfo", isBuiltIn: true, steps: steps(["CFO Sentinel Marcus", "Capital velocity management"], ["FP&A Oracle Demi", "ROI ranking"], ["Product Oracle Sasha", "Initiative assessment"]) },
  { name: "Intangible Value Monetization", description: "Convert hard-to-measure benefits — brand trust, employee morale, strategic optionality — into financial value using proxy metrics.", category: "cfo", isBuiltIn: true, steps: steps(["FP&A Oracle Demi", "Proxy metric design"], ["Brand Maven Priya", "Brand value modeling"], ["HR Director Amara", "Morale-to-productivity links"]) },
  { name: "AI Cost Optimization Engine", description: "Continuously reduce AI operational costs through intelligent model routing, response caching, and prompt compression.", category: "cfo", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Model routing optimization"], ["CFO Sentinel Marcus", "Cost curve management"], ["FP&A Oracle Demi", "Infrastructure efficiency"]) },

  // ─── CIO / CTO / TECHNOLOGY (51–65) ─────────────────────────────────────
  { name: "Multiagent System Architecture", description: "Deploy collaborative AI agents that pursue individual objectives or work together on shared goals across enterprise workflows.", category: "cio_cto", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Orchestration layer design"], ["Operator Rex", "Workflow automation"], ["Product Oracle Sasha", "Use case selection"]) },
  { name: "Hybrid Computing Architecture", description: "Combine CPUs, GPUs, and specialized processors — routing workloads to optimal hardware based on task type and cost.", category: "cio_cto", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Infrastructure architecture"], ["CISO Sentinel Nova", "Security integration"], ["FP&A Oracle Demi", "Cost modeling"]) },
  { name: "AI Security Platform Deployment", description: "Protect against AI-specific risks including prompt injection, data leakage, and rogue agent actions with centralized governance.", category: "cio_cto", isBuiltIn: true, steps: steps(["CISO Sentinel Nova", "Platform deployment"], ["Tech Visionary Zara", "Integration design"], ["General Counsel Alexis", "Policy compliance"]) },
  { name: "Digital Provenance Implementation", description: "Track AI-generated content origin and authenticity with watermarking, content credentials, and full audit trails.", category: "cio_cto", isBuiltIn: true, steps: steps(["General Counsel Alexis", "Compliance framework"], ["CISO Sentinel Nova", "Technical implementation"], ["Brand Maven Priya", "Content credentialing"]) },
  { name: "Geopatriation Infrastructure", description: "Shift workloads to sovereign clouds, regional providers, or on-premises infrastructure to meet data residency requirements.", category: "cio_cto", isBuiltIn: true, steps: steps(["CISO Sentinel Nova", "Data residency compliance"], ["Tech Visionary Zara", "Infrastructure migration"], ["General Counsel Alexis", "Regional regulation mapping"]) },
  { name: "AI Maturity Assessment", description: "Measure readiness across governance, data, technology, and skills dimensions — then prioritize investments by gap impact.", category: "cio_cto", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Maturity scoring"], ["CISO Sentinel Nova", "Governance audit"], ["HR Director Amara", "Skills gap analysis"]) },
  { name: "Preemptive Cybersecurity Operations", description: "Shift from reactive to proactive defense with AI-powered threat hunting, programmatic denial, and deception technologies.", category: "cio_cto", isBuiltIn: true, steps: steps(["CISO Sentinel Nova", "SecOps deployment"], ["Risk Warden Okafor", "Threat modeling"], ["Tech Visionary Zara", "Defense architecture"]) },
  { name: "Synthetic Data Generation", description: "Create safe, scalable training data using privacy-preserving synthetic generation — especially critical in regulated industries.", category: "cio_cto", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Data pipeline design"], ["General Counsel Alexis", "Privacy compliance"], ["Product Oracle Sasha", "Training data specifications"]) },
  { name: "Edge AI Deployment", description: "Run models locally on devices and edge nodes for real-time responses, enhanced privacy, and offline availability.", category: "cio_cto", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Edge architecture design"], ["CISO Sentinel Nova", "Privacy engineering"], ["Product Oracle Sasha", "Application requirements"]) },
  { name: "Domain-Specific LLM Development", description: "Train or fine-tune AI models on proprietary data for industry, function, or process-specific performance advantages.", category: "cio_cto", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Model training strategy"], ["Product Oracle Sasha", "Use case specification"], ["General Counsel Alexis", "Data usage compliance"]) },
  { name: "Hybrid AI-Quantum Integration", description: "Prepare for quantum-classical hybrid workflows — particularly for optimization, logistics, and scientific simulation.", category: "cio_cto", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Quantum use case identification"], ["FP&A Oracle Demi", "Investment planning"], ["Product Oracle Sasha", "Pipeline development"]) },
  { name: "AI Observability Stack", description: "Deploy prompt-level visibility into all AI usage — detect shadow AI, measure actual value, and identify risk.", category: "cio_cto", isBuiltIn: true, steps: steps(["CISO Sentinel Nova", "Observability deployment"], ["Tech Visionary Zara", "Usage analytics"], ["Operator Rex", "Workflow insight extraction"]) },
  { name: "Multi-LLM Routing Optimization", description: "Route queries to the optimal AI model based on task complexity — balancing quality and cost automatically.", category: "cio_cto", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Routing logic design"], ["CFO Sentinel Marcus", "Cost optimization"], ["Product Oracle Sasha", "Quality benchmarking"]) },
  { name: "Infrastructure Bottleneck Elimination", description: "Audit and remove the specific GPU, pipeline, latency, or storage constraints limiting AI scale.", category: "cio_cto", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Bottleneck auditing"], ["FP&A Oracle Demi", "Investment prioritization"], ["Operator Rex", "Throughput optimization"]) },
  { name: "Sovereign Cloud Strategy", description: "Build or partner for regional AI infrastructure that enables globally distributed, locally compliant AI operations.", category: "cio_cto", isBuiltIn: true, steps: steps(["Tech Visionary Zara", "Sovereign cloud partnerships"], ["General Counsel Alexis", "Regional compliance"], ["CISO Sentinel Nova", "Security architecture"]) },

  // ─── COO / OPERATIONS (66–80) ─────────────────────────────────────────────
  { name: "End-to-End Process Redesign", description: "Rebuild core workflows with AI embedded at every step — not layered on top of existing processes.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Workflow redesign"], ["Product Oracle Sasha", "AI integration points"], ["Tech Visionary Zara", "Technology enablement"]) },
  { name: "Autonomous Exception Handling", description: "Train AI to recognize and resolve common process exceptions automatically — humans handle only novel edge cases.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Exception pattern training"], ["Product Oracle Sasha", "Resolution automation"], ["Risk Warden Okafor", "Edge case escalation rules"]) },
  { name: "Predictive Maintenance Network", description: "Predict equipment failures before they occur using IoT sensor data and AI models — scheduling maintenance only when needed.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Sensor data integration"], ["Tech Visionary Zara", "Predictive model deployment"], ["FP&A Oracle Demi", "Maintenance cost optimization"]) },
  { name: "Dynamic Workforce Allocation", description: "Match human talent to tasks in real-time — routing routine work to AI agents, complex work to the right humans.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Allocation optimization"], ["HR Director Amara", "Skills matching"], ["Tech Visionary Zara", "AI routing infrastructure"]) },
  { name: "Real-Time Supply Chain Control Tower", description: "End-to-end supply chain visibility with AI recommendations for disruption response within 15 minutes.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Supply chain monitoring"], ["Risk Warden Okafor", "Disruption alerts"], ["FP&A Oracle Demi", "Cost impact analysis"]) },
  { name: "Intelligent Document Processing", description: "Extract, classify, and action information from any document — invoices, contracts, forms — without human touch.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Document pipeline automation"], ["Product Oracle Sasha", "Data extraction logic"], ["General Counsel Alexis", "Contract processing"]) },
  { name: "AI-Augmented Quality Control", description: "Detect defects at machine speed using computer vision AI — escalating only edge cases for human review.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Inspection pipeline"], ["Tech Visionary Zara", "Computer vision deployment"], ["Product Oracle Sasha", "Quality threshold calibration"]) },
  { name: "Automated Regulatory Compliance Monitoring", description: "Continuously check operations against regulatory requirements in real-time — generating audit trails automatically.", category: "coo", isBuiltIn: true, steps: steps(["General Counsel Alexis", "Regulatory requirement mapping"], ["Operator Rex", "Compliance monitoring"], ["Risk Warden Okafor", "Violation flagging"]) },
  { name: "Intelligent Scheduling & Routing", description: "Optimize complex scheduling for field service, logistics, or meetings — updating in real-time as conditions change.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Schedule optimization"], ["Tech Visionary Zara", "Constraint modeling"], ["FP&A Oracle Demi", "Cost efficiency analysis"]) },
  { name: "Cognitive Process Automation", description: "Automate judgment-dependent processes using LLMs — document classification, email triage, approval recommendations.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Cognitive automation deployment"], ["Product Oracle Sasha", "Judgment task mapping"], ["Tech Visionary Zara", "LLM integration"]) },
  { name: "Operational Digital Twin", description: "Simulate operations to test process changes, capacity adjustments, and disruption responses before deploying to production.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Digital twin modeling"], ["Tech Visionary Zara", "Simulation infrastructure"], ["FP&A Oracle Demi", "Change impact analysis"]) },
  { name: "Intelligent Inventory Optimization", description: "Forecast demand at SKU-location level — optimizing safety stock and reorder points using AI across the full network.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Demand forecasting"], ["FP&A Oracle Demi", "Working capital optimization"], ["Tech Visionary Zara", "Inventory model deployment"]) },
  { name: "Automated Vendor Risk Management", description: "Continuously monitor vendor financial health, security posture, and geopolitical exposure — flagging deterioration early.", category: "coo", isBuiltIn: true, steps: steps(["Risk Warden Okafor", "Vendor risk scoring"], ["Operator Rex", "Performance monitoring"], ["General Counsel Alexis", "Contract compliance"]) },
  { name: "Intelligent Workload Balancing", description: "Distribute work optimally across human and AI resources — learning from outcomes to continuously improve routing decisions.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Workload analysis"], ["HR Director Amara", "Human capacity planning"], ["Tech Visionary Zara", "AI routing optimization"]) },
  { name: "Continuous Process Mining", description: "Automatically discover optimization opportunities by analyzing event logs to reveal actual process flows vs. assumed ones.", category: "coo", isBuiltIn: true, steps: steps(["Operator Rex", "Process log analysis"], ["Tech Visionary Zara", "Mining tool deployment"], ["Product Oracle Sasha", "Recommendation generation"]) },

  // ─── CHRO / HUMAN RESOURCES (81–95) ─────────────────────────────────────
  { name: "AI Literacy at Scale", description: "Build foundational AI skills across all employees — covering prompt engineering, AI limitations, and responsible use.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Training curriculum design"], ["Tech Visionary Zara", "AI fundamentals instruction"], ["CISO Sentinel Nova", "Responsible use guidelines"]) },
  { name: "Expert-First AI Augmentation", description: "Amplify your most experienced employees — deploying AI as a force multiplier rather than a replacement strategy.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Expert identification"], ["Product Oracle Sasha", "AI tool matching"], ["Operator Rex", "Augmentation workflows"]) },
  { name: "AI Role Redesign", description: "Redefine every role for human-AI collaboration — identifying which tasks belong to AI, which to humans, and which are hybrid.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Role analysis"], ["Operator Rex", "Process decomposition"], ["Product Oracle Sasha", "AI capability mapping"]) },
  { name: "Continuous Skills Ontology", description: "Build an AI-powered skills map updated daily from project work, training completions, and manager feedback.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Ontology design"], ["Tech Visionary Zara", "Automated data collection"], ["Operator Rex", "Matching engine deployment"]) },
  { name: "AI-Augmented Talent Acquisition", description: "AI screens, interviews, and assesses candidates — freeing humans to focus on final rounds and relationship-building.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Screening automation"], ["Closer King Rivera", "Candidate engagement"], ["Tech Visionary Zara", "Assessment tools"]) },
  { name: "Flight Risk Prediction", description: "Identify at-risk employees before they resign using engagement signals, compensation benchmarks, and career progression analysis.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Risk scoring model"], ["FP&A Oracle Demi", "Replacement cost analysis"], ["Risk Warden Okafor", "Early intervention triggers"]) },
  { name: "Personalized Career Pathing", description: "Provide AI-recommended career moves for every employee based on skills, interests, performance, and open roles.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Career path modeling"], ["Operator Rex", "Internal opportunity matching"], ["FP&A Oracle Demi", "Development ROI analysis"]) },
  { name: "AI Performance Management", description: "Replace annual reviews with continuous, data-driven performance insights — AI analyzes outputs, humans coach people.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Performance data collection"], ["Operator Rex", "Output analysis"], ["Product Oracle Sasha", "Feedback delivery system"]) },
  { name: "Multi-Job Employee Support", description: "Build policies, scheduling, and compensation frameworks for employees working multiple simultaneous roles.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Policy design"], ["Operator Rex", "Scheduling optimization"], ["General Counsel Alexis", "Compliance framework"]) },
  { name: "Change Management at Scale", description: "Drive AI adoption as a company-wide change program — deploying champions, communication campaigns, and feedback loops.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Change program design"], ["Brand Maven Priya", "Communication campaigns"], ["Operator Rex", "Adoption measurement"]) },
  { name: "Ethical AI Use Policy", description: "Establish enterprise-wide AI use guidelines embedding transparency, fairness, and accountability from the outset.", category: "chro", isBuiltIn: true, steps: steps(["General Counsel Alexis", "Policy drafting"], ["HR Director Amara", "Training and rollout"], ["CISO Sentinel Nova", "Technical safeguards"]) },
  { name: "AI Fluency for Leadership", description: "Ensure every leader can manage AI-augmented teams — interpreting AI recommendations and maintaining human judgment.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Leadership training"], ["Chairman Atlas", "Strategic AI context"], ["Magnus Drake", "Judgment frameworks"]) },
  { name: "Workforce Planning with AI Scenarios", description: "Model workforce needs under different AI adoption scenarios over 3-5 years — building transition plans for affected roles.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Scenario modeling"], ["FP&A Oracle Demi", "Cost projection"], ["Operator Rex", "Transition plan design"]) },
  { name: "Inclusion & Bias Monitoring", description: "Continuously audit AI-HR systems for disparate impact across recruiting, promotion, and performance — correcting detected bias.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Bias audit design"], ["General Counsel Alexis", "Legal compliance"], ["Risk Warden Okafor", "Impact assessment"]) },
  { name: "AI-Augmented Learning & Development", description: "Deliver personalized, just-in-time learning for every employee — adapting content difficulty based on skills gaps and role goals.", category: "chro", isBuiltIn: true, steps: steps(["HR Director Amara", "Learning path design"], ["Product Oracle Sasha", "Content recommendation engine"], ["Tech Visionary Zara", "Adaptive delivery platform"]) },

  // ─── CMO / MARKETING (96–105) ─────────────────────────────────────────────
  { name: "Generative Engine Optimization (GEO)", description: "Get your brand cited by AI answer engines — ChatGPT, Gemini, Perplexity — as traditional search traffic shifts to generative AI.", category: "cmo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Content optimization for AI citation"], ["Product Oracle Sasha", "Structured data strategy"]) },
  { name: "AI-Generated Content at Scale", description: "Produce personalized blogs, emails, case studies, and press releases for every segment — optimized for both GEO and brand voice.", category: "cmo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Content strategy and brand voice"], ["Product Oracle Sasha", "Segment personalization"]) },
  { name: "Brand Sentiment AI Monitoring", description: "Real-time brand health tracking across social media, news, and forums — alerting within minutes of significant sentiment shifts.", category: "cmo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Sentiment monitoring"], ["Risk Warden Okafor", "Crisis alert triggers"]) },
  { name: "Customer Journey AI Orchestration", description: "Coordinate website, email, ads, and sales through AI — predicting intent and executing next-best-action across every touchpoint.", category: "cmo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Journey mapping"], ["Closer King Rivera", "Conversion optimization"], ["Product Oracle Sasha", "Personalization engine"]) },
  { name: "AI-Driven Market Segmentation", description: "Discover hidden customer segments by analyzing behavioral, demographic, and firmographic data with unsupervised AI clustering.", category: "cmo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Segmentation analysis"], ["Product Oracle Sasha", "Cluster interpretation"]) },
  { name: "Predictive Customer Lifetime Value", description: "Forecast CLV for every customer using purchase history, engagement, and external signals — enabling differentiated treatment by value.", category: "cmo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "CLV modeling"], ["FP&A Oracle Demi", "Revenue projection"], ["Closer King Rivera", "High-value retention strategy"]) },
  { name: "AI Campaign Optimization", description: "Monitor, test, and reallocate campaign budgets across channels in real-time — always chasing the highest-ROI tactic.", category: "cmo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Campaign performance analysis"], ["FP&A Oracle Demi", "Budget reallocation"], ["Closer King Rivera", "Conversion tactics"]) },
  { name: "Competitive Intelligence Automation", description: "Continuously scan AI engines for competitor mentions, pricing changes, product launches, and positioning shifts — delivered weekly.", category: "cmo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Competitive positioning"], ["Growth Hawk Yusuf", "Market move intelligence"]) },
  { name: "AI-Generated Visual Content", description: "Produce images, video, and 3D content at scale using generative visual AI — dramatically reducing production cost and time.", category: "cmo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Visual brand standards"], ["Tech Visionary Zara", "Generative media tooling"], ["Product Oracle Sasha", "Content pipeline"]) },
  { name: "Voice of Customer (VoC) AI", description: "Extract strategic insights from every customer interaction — support tickets, surveys, calls, reviews — with quarterly VoC reports.", category: "cmo", isBuiltIn: true, steps: steps(["Brand Maven Priya", "Insight synthesis"], ["Product Oracle Sasha", "Feedback loop design"], ["Operator Rex", "Data collection integration"]) },

  // ─── CPO / PRODUCT (106–115) ─────────────────────────────────────────────
  { name: "AI-First Product Development", description: "Rebuild products with AI embedded in core experiences — not added as a surface-level feature after the fact.", category: "cpo", isBuiltIn: true, steps: steps(["Product Oracle Sasha", "AI-native architecture design"], ["Tech Visionary Zara", "Core AI integration"], ["Brand Maven Priya", "User experience vision"]) },
  { name: "AI Feature Prioritization", description: "Make data-driven roadmap decisions by scoring potential features on impact, effort, and strategic alignment using AI analysis.", category: "cpo", isBuiltIn: true, steps: steps(["Product Oracle Sasha", "Feature scoring model"], ["FP&A Oracle Demi", "Impact-to-effort analysis"]) },
  { name: "User Behavior AI Analytics", description: "Understand how users actually use your product through AI analysis of clickstreams, sessions, and feature usage patterns.", category: "cpo", isBuiltIn: true, steps: steps(["Product Oracle Sasha", "Behavior analysis"], ["Tech Visionary Zara", "Analytics infrastructure"], ["Operator Rex", "Friction point identification"]) },
  { name: "AI-Augmented User Research", description: "Synthesize user interviews, surveys, usability tests, and analytics into personas, journey maps, and problem statements.", category: "cpo", isBuiltIn: true, steps: steps(["Product Oracle Sasha", "Research synthesis"], ["Brand Maven Priya", "Persona development"], ["Operator Rex", "Data collection automation"]) },
  { name: "Predictive User Churn", description: "Identify users likely to churn using usage patterns and account health — then deploy targeted interventions before they leave.", category: "cpo", isBuiltIn: true, steps: steps(["Product Oracle Sasha", "Churn prediction model"], ["Closer King Rivera", "Retention intervention design"], ["FP&A Oracle Demi", "Revenue impact analysis"]) },
  { name: "AI-Generated Product Requirements", description: "Draft product requirement documents from user feedback, competitive analysis, and market trends — ready for PM review.", category: "cpo", isBuiltIn: true, steps: steps(["Product Oracle Sasha", "PRD generation"], ["Brand Maven Priya", "User needs synthesis"]) },
  { name: "AI-Powered Prototyping", description: "Generate interactive prototypes from natural language descriptions — allowing rapid iteration before any code is written.", category: "cpo", isBuiltIn: true, steps: steps(["Product Oracle Sasha", "Prototype generation"], ["Tech Visionary Zara", "Technical specification"], ["Brand Maven Priya", "UX validation"]) },
  { name: "Automated Usability Testing", description: "AI agents navigate your product like real users — finding confusing flows and accessibility issues before launch.", category: "cpo", isBuiltIn: true, steps: steps(["Product Oracle Sasha", "Test scenario design"], ["Tech Visionary Zara", "AI agent deployment"], ["Operator Rex", "Issue triage"]) },
  { name: "Feature Impact Prediction", description: "Forecast how proposed features will affect adoption, engagement, and revenue before committing development resources.", category: "cpo", isBuiltIn: true, steps: steps(["Product Oracle Sasha", "Impact modeling"], ["FP&A Oracle Demi", "Revenue projection"], ["Tech Visionary Zara", "Technical feasibility"]) },
  { name: "Product-Led Growth AI", description: "Use AI to drive product adoption and expansion revenue — identifying upgrade-ready users and personalizing in-product messaging.", category: "cpo", isBuiltIn: true, steps: steps(["Product Oracle Sasha", "PLG signal detection"], ["Closer King Rivera", "Expansion strategy"], ["FP&A Oracle Demi", "Revenue expansion modeling"]) },

  // ─── CISO / SECURITY (116–120) ────────────────────────────────────────────
  { name: "AI Security Platform", description: "Deploy centralized protection for all AI applications — providing visibility, policy enforcement, and threat detection.", category: "ciso", isBuiltIn: true, steps: steps(["CISO Sentinel Nova", "Platform deployment and policy"], ["Tech Visionary Zara", "AI application inventory"], ["General Counsel Alexis", "Compliance alignment"]) },
  { name: "Preemptive Cyber Defense", description: "AI-powered threat hunting and automated containment — detecting and responding faster than human-only teams can react.", category: "ciso", isBuiltIn: true, steps: steps(["CISO Sentinel Nova", "Threat hunting and SecOps"], ["Risk Warden Okafor", "Attack scenario modeling"], ["Tech Visionary Zara", "Automated response infrastructure"]) },
  { name: "Prompt Injection Defense", description: "Protect LLM applications from prompt attacks using input validation, context isolation, and output monitoring.", category: "ciso", isBuiltIn: true, steps: steps(["CISO Sentinel Nova", "Attack pattern detection"], ["Tech Visionary Zara", "Validation framework"], ["Risk Warden Okafor", "Compromise scenario modeling"]) },
  { name: "AI Data Leakage Prevention", description: "Stop sensitive data — PII, financials, IP — from reaching AI endpoints when employees use external AI tools.", category: "ciso", isBuiltIn: true, steps: steps(["CISO Sentinel Nova", "DLP policy deployment"], ["General Counsel Alexis", "Data classification"], ["Tech Visionary Zara", "Endpoint protection"]) },
  { name: "AI Supply Chain Security", description: "Secure AI models and dependencies through model signing, dependency scanning, and provenance tracking across the full pipeline.", category: "ciso", isBuiltIn: true, steps: steps(["CISO Sentinel Nova", "Supply chain audit"], ["Tech Visionary Zara", "Dependency scanning"], ["Operator Rex", "Pipeline security"]) },
];

export async function seedPlaybooks(): Promise<void> {
  const existing = await db
    .select({ name: missionPlaybooksTable.name })
    .from(missionPlaybooksTable)
    .where(eq(missionPlaybooksTable.isBuiltIn, true));

  const existingNames = new Set(existing.map((r) => r.name));
  const toInsert = BUILT_IN_PLAYBOOKS.filter((p) => !existingNames.has(p.name));

  if (toInsert.length === 0) {
    console.log("[seed] Playbooks: all built-ins already seeded");
    return;
  }

  await db.insert(missionPlaybooksTable).values(
    toInsert.map((p) => ({
      name: p.name,
      description: p.description,
      category: p.category,
      isBuiltIn: true,
      steps: p.steps,
    }))
  );

  console.log(`[seed] Playbooks: seeded ${toInsert.length} built-in playbook(s)`);
}
