import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import botsRouter from "./bots";
import conversationsRouter from "./conversations";
import boardroomRouter from "./boardroom";
import clientsRouter from "./clients";
import journalRouter from "./journal";
import blogRouter from "./blog";
import partnerRouter from "./partner";
import translateRouter from "./translate";
import taskSessionsRouter from "./task-sessions";
import memoryRouter from "./memory";
import complianceRouter from "./compliance";
import clientIntegrationsRouter from "./client-integrations";
import piratemonsterRouter from "./piratemonster";
import receptionistRouter from "./receptionist";
import auditRouter from "./audit";
import { llmRateLimit } from "../middleware/rate-limit";
import { requireRole } from "../middleware/auth";
import roiRouter from "./roi";
import billingRouter from "./billing";
import webhooksRouter from "./webhooks";
import prospectsRouter from "./prospects";
import storageRouter from "./storage";
import userPreferencesRouter from "./user-preferences";
import governanceRouter from "./governance";
import knowledgeBaseRouter from "./knowledge-base";
import documentsRouter from "./documents";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(botsRouter);
router.use(conversationsRouter);
router.use(boardroomRouter);
router.use(clientsRouter);
router.use(journalRouter);
router.use(blogRouter);
router.use(partnerRouter);
router.use(translateRouter);
router.use(taskSessionsRouter);
router.use(memoryRouter);
router.use(complianceRouter);
router.use(clientIntegrationsRouter);
router.use(piratemonsterRouter);
router.use(receptionistRouter);
router.use(auditRouter);
router.use(roiRouter);
router.use(billingRouter);
router.use(webhooksRouter);
router.use(prospectsRouter);
router.use(storageRouter);
router.use(userPreferencesRouter);
router.use(governanceRouter);
router.use(knowledgeBaseRouter);
router.use(documentsRouter);

export default router;
