import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import botsRouter from "./bots";
import conversationsRouter from "./conversations";
import boardroomRouter from "./boardroom";
import clientsRouter from "./clients";
import journalRouter from "./journal";
import blogRouter from "./blog";
import partnerRouter from "./partner";
import translateRouter from "./translate";
import taskSessionsRouter from "./task-sessions";
import memoryRouter from "./memory";
import complianceRouter from "./compliance";
import clientIntegrationsRouter from "./client-integrations";
import piratemonsterRouter from "./piratemonster";
import receptionistRouter from "./receptionist";
import auditRouter from "./audit";
import { llmRateLimit } from "../middleware/rate-limit";
import { requireRole } from "../middleware/auth";
import roiRouter from "./roi";
import billingRouter from "./billing";
import webhooksRouter from "./webhooks";
import prospectsRouter from "./prospects";
import prospectingRouter from "./prospecting";
import prospectingApiRouter from "./prospecting-api";
import storageRouter from "./storage";
import userPreferencesRouter from "./user-preferences";
import governanceRouter from "./governance";
import knowledgeBaseRouter from "./knowledge-base";
import documentsRouter from "./documents";
import pipelinesRouter from "./pipelines";
import triggersRouter from "./triggers";
import commandCenterRouter from "./command-center";
import analyticsRouter from "./analytics";
import demoRouter from "./demo";
import onboardingRouter from "./onboarding";
import clientPortalRouter from "./client-portal";
import packsRouter from "./packs";
import bingolingoRouter from "./bingolingo";
import marketplaceRouter from "./marketplace";
import ssoRouter from "./sso";
import scimRouter from "./scim";
import orgAdminRouter from "./org-admin";
import proposalsRouter from "./proposals";
import notificationsRouter from "./notifications";
import clientHealthRouter from "./client-health";
import pushTokensRouter from "./push-tokens";
import developerRouter from "./developer";
import voiceIntelligenceRouter from "./voice-intelligence";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(demoRouter);
router.use(botsRouter);
router.use(conversationsRouter);
router.use(boardroomRouter);
router.use(clientsRouter);
router.use(journalRouter);
router.use(blogRouter);
router.use(partnerRouter);
router.use(translateRouter);
router.use(taskSessionsRouter);
router.use(memoryRouter);
router.use(complianceRouter);
router.use(clientIntegrationsRouter);
router.use(piratemonsterRouter);
router.use(receptionistRouter);
router.use(auditRouter);
router.use(roiRouter);
router.use(billingRouter);
router.use(webhooksRouter);
router.use(prospectsRouter);
router.use(prospectingRouter);
router.use(prospectingApiRouter);
router.use(storageRouter);
router.use(userPreferencesRouter);
router.use(governanceRouter);
router.use(knowledgeBaseRouter);
router.use(documentsRouter);
router.use(pipelinesRouter);
router.use(triggersRouter);
router.use(commandCenterRouter);
router.use(analyticsRouter);
router.use(onboardingRouter);
router.use(clientPortalRouter);
router.use(packsRouter);
router.use(bingolingoRouter);
router.use(marketplaceRouter);
router.use(ssoRouter);
router.use(scimRouter);
router.use(orgAdminRouter);
router.use(proposalsRouter);
router.use(notificationsRouter);
router.use(clientHealthRouter);
router.use(pushTokensRouter);
router.use(developerRouter);
router.use(voiceIntelligenceRouter);

export default router;
