export const narration: string[] = [
  // Slide 01 — Cover
  `Good [morning / afternoon], and welcome. What you're about to see is the five-year strategic plan for GalaxyBots.ai — a company we believe will define an entirely new software category. This deck represents our blueprint for the period 2026 through 2030. Everything here is confidential and intended for board distribution only. Let's begin.`,

  // Slide 02 — Executive Summary
  `Our mission is straightforward: build the world's largest fleet of autonomous AI executives and make Fortune 500-level strategic intelligence accessible to every business on earth — not just those that can afford a full C-suite. By the end of Year 1, we are targeting one-point-two million dollars in Annual Recurring Revenue, powered by a suite of four interconnected products: GalaxyBots.ai, our virtual boardroom; BingoLingo.ai, our AEO intelligence engine; Prospector, our autonomous B2B pipeline; and the GalaxyBots Mobile Command Center.`,

  // Slide 03 — The Problem
  `The problem is structural. A single elite C-suite costs between one and five million dollars per year in salary alone — completely out of reach for the thirty-two million small and mid-size enterprises that make up the backbone of the global economy. A CMO costs a quarter million. A CFO, three hundred thousand. A CISO, two-eighty. These aren't luxuries — they're the decisions that determine whether a company survives. The problem is not AI capability. The problem is accessibility, orchestration, and trust.`,

  // Slide 04 — Vision
  `We are not building chatbots. We are defining a new category: the AI Executive Layer. Imagine a single founder commanding a global conglomerate from their phone — with a full C-suite of AI directors who work autonomously around the clock, collaborate with each other in virtual boardrooms, and remember every decision the business has ever made. Three pillars: Autonomous — they work while you sleep. Interconnected — they collaborate in real time. Persistent — they accumulate institutional memory that never leaves.`,

  // Slide 05 — Market Opportunity
  `The market opportunity is enormous. By 2030, the global AI SaaS market reaches five hundred billion dollars. Our Serviceable Addressable Market — thirty-two million SMEs and five hundred thousand agencies — is one-fifty billion. Our Serviceable Obtainable Market, the beachhead of fifty thousand U.S. growth-stage companies at three thousand dollars ACV, is a hundred-and-fifty million. We built this bottom-up using LinkedIn and U.S. Census cross-referencing, AI adoption curve modeling, and a wholesale partner channel that gives us a ten-times reach multiplier.`,

  // Slide 06 — Competition
  `When we map the competitive landscape on two axes — autonomy and specialization — something striking emerges. Generic chatbots like ChatGPT and Claude are high-autonomy but completely unspecialized. Productivity co-pilots like Microsoft 365 are low on both. CRM-specific AI like Salesforce Einstein is specialized but low-autonomy. The upper-right quadrant — high autonomy, high specialization, for the SME sector — is completely unoccupied. That is where GalaxyBots.ai sits, and we intend to own it. Our wedge: a white-label partner channel and proprietary AEO intelligence that competitors cannot easily replicate.`,

  // Slide 07 — Infrastructure
  `We are LLM-agnostic buyers, not foundation model trainers. We route Claude 3.5, GPT-4o, and other best-in-class models by task type — giving us maximum resilience, lower capital expenditure, and faster iteration cycles. Our proprietary value sits in three layers above the model: agentic orchestration via multi-agent LangGraph workflows that reason and adapt; institutional memory that accumulates long-term, company-specific intelligence; and the Prospector data flywheel — a proprietary extraction pattern library that compounds in value every single day.`,

  // Slide 08 — GalaxyBots.ai
  `GalaxyBots.ai is the central nervous system. A multi-tenant SaaS platform that hosts an entire executive suite — fifty-one AI directors, each fully specialized from CMO to CISO. What makes them different from generic LLM wrappers is that they collaborate. They have unique personas. They remember past boardroom sessions. They can trigger external tools — Prospector, BingoLingo — autonomously, without being asked. The Approval Hub gives human leadership governance and ROI visibility. It is white-label ready and ROI-driven from day one.`,

  // Slide 09 — BingoLingo.ai
  `BingoLingo.ai is our AEO intelligence engine, and it introduces a proprietary metric called the Cloud 9 Score — the industry's first standardized measurement of a brand's presence across AI answer engines: ChatGPT, Perplexity, Claude, and Gemini. Three capabilities: scanning and scoring how LLMs perceive and recommend your brand; a content attribution loop that identifies which content directly drives AI recommendations; and a strategic flywheel that feeds high-intent data back to the CMO Bot and the Prospector. BingoLingo is the Bloomberg Terminal of AI brand presence.`,

  // Slide 10 — Prospector
  `Prospector is more than a feature — it is a standalone revenue product. It is an autonomous B2B intelligence engine that replaces manual lead generation. The pipeline has four stages: Discover, through multi-source identification; Enrich, via a six-step agentic extraction process; Validate, using a critic-reviewer loop; and ICP Score, for strategic qualification. Cost per lead: under fifty cents. Accuracy target: above eighty-five percent. The data flywheel means every job the engine runs teaches it something new, creating a compounding moat comparable to Clay.com — but built specifically for agentic orchestration and white-label distribution.`,

  // Slide 11 — Mobile
  `GalaxyBots Mobile is the Universal Command Center — your entire AI executive fleet in your pocket. Built on Expo React Native, fully compatible with iOS and Android. It enables real-time governance approvals with push-token security, live ROI reporting, and universal bot directives that cascade across your entire fleet instantly. Whether you are on a plane, in a meeting, or across the world, your AI executives are never out of reach.`,

  // Slide 12 — Business Model
  `Our pricing is built for the SME market with a clear path to enterprise. Starter at nine-ninety-nine per month. Pro — our most popular tier — at four-thousand-nine-ninety-nine. Scale at nine-thousand-nine-ninety-nine, billed annually. Beyond subscriptions, we capture usage upside through credit overages, high-velocity revenue through white-label wholesale partnerships, and premium add-ons through custom bot fabrication. Blended Annual Contract Value target: thirty-six thousand dollars.`,

  // Slide 13 — Unit Economics
  `Our unit economics tell a compelling story. Gross margin target of eighty-two percent by Year 2. LTV to CAC ratio of eight-to-one by Year 3. Customer payback period under twelve months by Year 2. And Net Revenue Retention above one-ten percent through credit expansion. We achieve this through three cost controls: optimized inference routing that cuts token costs forty percent without sacrificing quality; partner distribution that drives near-zero CAC for partner-originated clients; and Prospector cost-per-lead that drops as the extraction library matures.`,

  // Slide 14 — Financial Projections
  `Here is the base case in five numbers. Twenty twenty-six: one-point-two million ARR, eighty direct clients, twelve agency partners — beachhead validation. Twenty twenty-seven: four-point-eight million, two-fifty clients, forty partners — scale and partner maturity. Twenty twenty-eight: fourteen million, six hundred clients, one-twenty partners — market leader position. Twenty twenty-nine: thirty-eight million, fourteen hundred clients, three hundred partners — international expansion begins. Twenty thirty: ninety million ARR, three thousand clients, seven hundred partners — IPO and acquisition readiness. The critical assumption: the partner channel drives fifty percent of all new ARR from Year 3 onward.`,

  // Slide 15 — Scenario Modeling
  `We modeled three scenarios. In the bear case — assuming regulatory headwinds, slow partner adoption, and LLM API inflation — we still reach forty-two million ARR by twenty-thirty through direct sales. The base case, our current trajectory, hits ninety million driven by standard partner growth, global SME adoption, and NRR expansion above one-ten percent. The bull case — if the partner channel breaks out, Prospector exits as a standalone product, and we capture early enterprise licensing — we reach one-eighty million. The key variables are partner conversion rate, standalone pricing adoption, and international expansion timing.`,

  // Slide 16 — GTM Strategy
  `Our go-to-market runs on three engines. Content-led: BingoLingo self-demonstrates its own value — AEO reports generate massive inbound interest for the full GalaxyBots suite. Partner-led: white-label agencies are our primary distribution channel; when they onboard a client through their own trust network, our customer acquisition cost is effectively zero. Community-led: the GalaxyBots Commander community creates peer referrals and viral advocacy. And underneath all three sits the Partner Flywheel: partner signs, deploys to clients, clients see ROI, partner upgrades — a self-reinforcing engine that compounds every quarter.`,

  // Slide 17 — Year 1 Priorities
  `Twenty twenty-six has five non-negotiable priorities. First: close our first ten flagship white-label agency partners. Second: deploy Prospector's fully autonomous pipeline through all four phases. Third: achieve a ninety-day Net Revenue Retention above one-ten percent. Fourth: publish three AEO case studies proving the Cloud 9 Score delivers measurable ROI. Fifth: ship the Universal Command Center v1 to both App Stores. Our North Star this year is clear — transition from a tools company to an Infrastructure-as-an-Executive provider for the SME mid-market.`,

  // Slide 18 — Roadmap
  `The five-year roadmap runs across four parallel tracks. Platform: White-label Partner Portal in twenty-twenty-six, Governance v2 in twenty-twenty-seven, Enterprise Pack in twenty-twenty-eight, Global SSO in twenty-twenty-nine, and IPO readiness in twenty-thirty. Content: AEO Engine v1, Cloud 9 Score, Attribution Loop, BingoLingo API, then Category Dominance. Intelligence: Prospector v1, a Learning Agent, a potential Standalone exit, proprietary dataset, and the AI Market Index. Mobile: Command Center, Fleet Health, Approval Engine, Native Agent, and Universal Interface. Every track is interconnected — progress on one accelerates the others.`,

  // Slide 19 — Competitive Moat
  `What makes GalaxyBots defensible? Four compounding moats. The Data Flywheel: Prospector accumulates proprietary B2B enrichment data that improves with every job — a moat that widens daily. Institutional Memory: each client instance builds up thirty-six-plus months of company-specific context, making switching costs compound quarterly. Distribution Network: seven hundred agency partners by Year 5 creates a locked channel that would take competitors years to replicate. And AEO Category Ownership: by defining the Cloud 9 Score, BingoLingo becomes the reference product for AI presence — the Bloomberg of AEO. As we like to say: OpenAI builds the engine. We build the car, the dealership network, and the exclusive fuel supply.`,

  // Slide 20 — Risks & Mitigations
  `We have modeled our five principal risks with full mitigation strategies. LLM API cost inflation — medium probability, high impact — mitigated by multi-provider routing and pass-through credit pricing. Big Tech market entry — medium probability, high impact — mitigated by our focus on orchestration, memory, and the agency distribution channel that large platforms cannot easily enter. Partner adoption lag — medium probability, medium impact — mitigated by front-loading incentives and running a parallel direct sales motion. Regulatory tightening — low-to-medium probability — mitigated by our KiloPro compliance layer and localized data residency. And Prospector data plateau — low probability — mitigated by a continuous Learning Agent and human review queue.`,

  // Slide 21 — Team & Culture
  `We are an AI-native organization. Today we have twelve human team members and fifty-one AI directors — a fifty-one-to-one bot-to-human ratio. Our leadership philosophy is Commanders, not managers. Every human is expected to be directing a fleet of at least ten autonomous agents within their first ninety days. In Year 1, we are making three critical hires: a Head of Partner Success to drive agency relationships, a Head of Growth for BingoLingo, and a Senior ML and AI Engineer to take Prospector to its next phase. Our values are simple: Autonomy, Proof-of-Value, Intelligence for Everyone.`,

  // Slide 22 — Exit & Ask
  `By Year 5, we see three clear paths to liquidity. Strategic acquisition — targets include Salesforce, HubSpot, ServiceNow, and SAP — in the five-hundred-million to two-billion-dollar range at eight to twelve times ARR. Series B or IPO — ninety million ARR at eighty-two percent gross margin creates a compelling public market narrative. Or profitable independence — the partner channel cash flow enables self-sustaining growth and management buyout options. Today we have one-twenty-five thousand in Monthly Recurring Revenue and fourteen pilot partners active. We are seeking strategic partners and growth capital to accelerate the Prospector expansion and secure the global agency distribution layer. The door is open. Let's build this together.`,
];
