ALTER TABLE clients ADD COLUMN IF NOT EXISTS website_url TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS industry TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS services_list TEXT[];
ALTER TABLE clients ADD COLUMN IF NOT EXISTS target_market TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS business_context TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS webhook_secret TEXT;
