import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useState, useRef } from "react";
import {
  Loader2,
  Phone,
  PhoneIncoming,
  PhoneOutgoing,
  Clock,
  AlertTriangle,
  ChevronDown,
  ChevronUp,
  FileText,
  MessageSquare,
  Mic,
  Upload,
  Download,
  Trash2,
  Filter,
} from "lucide-react";

const BASE = import.meta.env.BASE_URL.replace(/\/$/, "");

interface CallDebrief {
  id: number;
  callLogId: number;
  callerName: string | null;
  callerIntent: string | null;
  keyConcerns: string | null;
  urgencyScore: number | null;
  recommendedAction: string | null;
  followUpMessage: string | null;
  isNewProspect: number;
  pipelineTriggered: number;
  createdAt: string;
}

interface CallLog {
  id: number;
  configId: number;
  twilioCallSid: string | null;
  direction: string;
  fromNumber: string | null;
  toNumber: string | null;
  status: string;
  durationSeconds: number | null;
  transcriptText: string | null;
  transcriptSummary: string | null;
  createdAt: string;
  debrief: CallDebrief | null;
}

interface VoiceScript {
  id: number;
  scriptType: string;
  title: string;
  objective: string | null;
  scriptContent: string;
  generatedBy: string | null;
  metadata: Record<string, unknown> | null;
  createdAt: string;
}

interface MeetingRecording {
  id: number;
  title: string;
  durationSeconds: number | null;
  transcriptText: string | null;
  summary: Record<string, unknown> | null;
  status: string;
  originalFilename: string | null;
  createdAt: string;
}

const URGENCY_STYLES: Record<number, string> = {
  1: "bg-green-500/10 text-green-400 border-green-500/30",
  2: "bg-blue-500/10 text-blue-400 border-blue-500/30",
  3: "bg-yellow-500/10 text-yellow-400 border-yellow-500/30",
  4: "bg-orange-500/10 text-orange-400 border-orange-500/30",
  5: "bg-red-500/10 text-red-400 border-red-500/30",
};

function formatDuration(seconds: number | null): string {
  if (!seconds) return "N/A";
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return mins > 0 ? `${mins}m ${secs}s` : `${secs}s`;
}

function downloadScript(script: VoiceScript) {
  const meta = script.metadata as { tips?: string; estimatedDurationSeconds?: number; estimatedDurationMinutes?: number; keyTalkingPoints?: string[] } | null;
  let content = `${script.title}\n`;
  content += `Type: ${script.scriptType === "voicemail" ? "Voicemail Drop" : "Outbound Call Script"}\n`;
  content += `Generated by: ${script.generatedBy || "AI"}\n`;
  content += `Date: ${new Date(script.createdAt).toLocaleString()}\n`;
  if (meta?.estimatedDurationMinutes) content += `Estimated Duration: ${meta.estimatedDurationMinutes} minutes\n`;
  if (meta?.estimatedDurationSeconds) content += `Estimated Duration: ${meta.estimatedDurationSeconds} seconds\n`;
  content += `\n---\n\n${script.scriptContent}`;
  if (meta?.tips) content += `\n\n---\nDelivery Tips: ${meta.tips}`;
  if (meta?.keyTalkingPoints && meta.keyTalkingPoints.length > 0) {
    content += `\n\n---\nKey Talking Points:\n${meta.keyTalkingPoints.map(p => `- ${p}`).join("\n")}`;
  }

  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${script.title.replace(/[^a-zA-Z0-9]/g, "_")}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

function CallCard({ call, onGenerateDebrief, isGenerating }: {
  call: CallLog;
  onGenerateDebrief: (id: number) => void;
  isGenerating: boolean;
}) {
  const [expanded, setExpanded] = useState(false);

  return (
    <Card className="border-border/40">
      <CardContent className="p-4">
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-3">
            {call.direction === "inbound" ? (
              <PhoneIncoming className="w-4 h-4 text-cyan" />
            ) : (
              <PhoneOutgoing className="w-4 h-4 text-primary" />
            )}
            <div>
              <p className="text-sm font-tech font-bold">
                {call.fromNumber || "Unknown Caller"}
              </p>
              <p className="text-xs text-muted-foreground">
                {new Date(call.createdAt).toLocaleString()}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Badge variant="outline" className="text-[10px]">
              <Clock className="w-3 h-3 mr-1" />
              {formatDuration(call.durationSeconds)}
            </Badge>
            <Badge variant={call.status === "completed" ? "cyan" : "outline"} className="text-[10px]">
              {call.status}
            </Badge>
            {call.debrief?.urgencyScore && (
              <Badge variant="outline" className={`text-[10px] ${URGENCY_STYLES[call.debrief.urgencyScore] || ""}`}>
                Urgency: {call.debrief.urgencyScore}/5
              </Badge>
            )}
          </div>
        </div>

        {call.debrief && (
          <div className="mt-3 p-3 rounded-lg bg-secondary/50 border border-border/30 space-y-2">
            <div className="flex items-center gap-2 mb-1">
              <FileText className="w-3.5 h-3.5 text-primary" />
              <span className="text-xs font-tech uppercase text-muted-foreground">Call Debrief</span>
              {call.debrief.isNewProspect === 1 && (
                <Badge variant="outline" className="text-[9px] bg-cyan/10 text-cyan border-cyan/30">
                  New Prospect
                </Badge>
              )}
              {call.debrief.pipelineTriggered === 1 && (
                <Badge variant="outline" className="text-[9px] bg-green-500/10 text-green-400 border-green-500/30">
                  Pipeline Triggered
                </Badge>
              )}
            </div>
            {call.debrief.callerName && call.debrief.callerName !== "Unknown" && (
              <p className="text-xs"><span className="text-muted-foreground">Caller:</span> {call.debrief.callerName}</p>
            )}
            {call.debrief.callerIntent && (
              <p className="text-xs"><span className="text-muted-foreground">Intent:</span> {call.debrief.callerIntent}</p>
            )}
            {call.debrief.keyConcerns && (
              <p className="text-xs"><span className="text-muted-foreground">Concerns:</span> {call.debrief.keyConcerns}</p>
            )}
            {call.debrief.recommendedAction && (
              <p className="text-xs"><span className="text-muted-foreground">Next Action:</span> {call.debrief.recommendedAction}</p>
            )}
          </div>
        )}

        <div className="flex items-center gap-2 mt-3">
          {call.transcriptText && (
            <Button variant="ghost" size="sm" className="text-xs h-7" onClick={() => setExpanded(!expanded)}>
              {expanded ? <ChevronUp className="w-3 h-3 mr-1" /> : <ChevronDown className="w-3 h-3 mr-1" />}
              {expanded ? "Hide" : "Show"} Transcript
            </Button>
          )}
          {call.transcriptText && !call.debrief && (
            <Button
              variant="outline"
              size="sm"
              className="text-xs h-7"
              onClick={() => onGenerateDebrief(call.id)}
              disabled={isGenerating}
            >
              {isGenerating ? <Loader2 className="w-3 h-3 mr-1 animate-spin" /> : <FileText className="w-3 h-3 mr-1" />}
              Generate Debrief
            </Button>
          )}
          {call.debrief?.followUpMessage && (
            <Button variant="ghost" size="sm" className="text-xs h-7" onClick={() => setExpanded(!expanded)}>
              <MessageSquare className="w-3 h-3 mr-1" />
              Follow-up Draft
            </Button>
          )}
        </div>

        {expanded && (
          <div className="mt-3 space-y-3">
            {call.transcriptText && (
              <div className="p-3 rounded bg-black/30 border border-border/20">
                <p className="text-xs font-tech uppercase text-muted-foreground mb-2">Transcript</p>
                <p className="text-xs whitespace-pre-wrap font-mono leading-relaxed">{call.transcriptText}</p>
              </div>
            )}
            {call.debrief?.followUpMessage && (
              <div className="p-3 rounded bg-primary/5 border border-primary/20">
                <p className="text-xs font-tech uppercase text-muted-foreground mb-2">Suggested Follow-up Message</p>
                <p className="text-sm whitespace-pre-wrap">{call.debrief.followUpMessage}</p>
              </div>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function ScriptGenerator({ clientId }: { clientId: number }) {
  const queryClient = useQueryClient();
  const [scriptType, setScriptType] = useState<"outbound" | "voicemail">("outbound");
  const [title, setTitle] = useState("");
  const [objective, setObjective] = useState("");
  const [targetPersona, setTargetPersona] = useState("");
  const [desiredOutcome, setDesiredOutcome] = useState("");

  const { data: scripts, isLoading: scriptsLoading } = useQuery<VoiceScript[]>({
    queryKey: ["voiceScripts", clientId],
    queryFn: async () => {
      const res = await fetch(`${BASE}/api/voice/scripts/${clientId}`);
      if (!res.ok) throw new Error("Failed");
      return res.json();
    },
  });

  const generateMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(`${BASE}/api/voice/scripts`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ clientId, scriptType, title, objective, targetPersona, desiredOutcome }),
      });
      if (!res.ok) throw new Error("Failed to generate script");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["voiceScripts", clientId] });
      setTitle("");
      setObjective("");
      setTargetPersona("");
      setDesiredOutcome("");
    },
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: number) => {
      const res = await fetch(`${BASE}/api/voice/scripts/${id}`, { method: "DELETE" });
      if (!res.ok) throw new Error("Failed");
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["voiceScripts", clientId] }),
  });

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base font-display flex items-center gap-2">
            <Mic className="w-4 h-4 text-primary" />
            Script Generator
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="flex gap-2">
            <Button
              variant={scriptType === "outbound" ? "default" : "outline"}
              size="sm"
              onClick={() => setScriptType("outbound")}
              className="text-xs"
            >
              <PhoneOutgoing className="w-3 h-3 mr-1" />
              Outbound Script
            </Button>
            <Button
              variant={scriptType === "voicemail" ? "default" : "outline"}
              size="sm"
              onClick={() => setScriptType("voicemail")}
              className="text-xs"
            >
              <MessageSquare className="w-3 h-3 mr-1" />
              Voicemail Drop
            </Button>
          </div>
          <Input
            placeholder="Script title"
            value={title}
            onChange={e => setTitle(e.target.value)}
            className="text-sm"
          />
          <Textarea
            placeholder={scriptType === "voicemail"
              ? "What's the voicemail about? (e.g., Follow up on website inquiry about lawn care services)"
              : "Call objective (e.g., Qualify lead who downloaded our whitepaper on commercial landscaping)"
            }
            value={objective}
            onChange={e => setObjective(e.target.value)}
            rows={2}
            className="text-sm"
          />
          {scriptType === "outbound" && (
            <>
              <Input
                placeholder="Target persona (e.g., Property manager at mid-size commercial complex)"
                value={targetPersona}
                onChange={e => setTargetPersona(e.target.value)}
                className="text-sm"
              />
              <Input
                placeholder="Desired outcome (e.g., Book a site visit next week)"
                value={desiredOutcome}
                onChange={e => setDesiredOutcome(e.target.value)}
                className="text-sm"
              />
            </>
          )}
          <Button
            onClick={() => generateMutation.mutate()}
            disabled={generateMutation.isPending || !title || !objective}
            className="w-full"
            variant="glow"
          >
            {generateMutation.isPending ? (
              <Loader2 className="w-4 h-4 animate-spin mr-2" />
            ) : (
              <Mic className="w-4 h-4 mr-2" />
            )}
            Generate {scriptType === "voicemail" ? "Voicemail Script" : "Call Script"}
          </Button>
        </CardContent>
      </Card>

      {scriptsLoading && (
        <div className="flex justify-center py-4">
          <Loader2 className="w-5 h-5 animate-spin text-muted-foreground" />
        </div>
      )}

      {scripts && scripts.length > 0 && (
        <div className="space-y-3">
          {scripts.map(script => (
            <Card key={script.id} className="border-border/40">
              <CardContent className="p-4">
                <div className="flex items-start justify-between mb-2">
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <Badge variant="outline" className="text-[10px]">
                        {script.scriptType === "voicemail" ? "Voicemail" : "Outbound"}
                      </Badge>
                      {script.generatedBy && (
                        <span className="text-[10px] text-muted-foreground">by {script.generatedBy}</span>
                      )}
                    </div>
                    <h4 className="text-sm font-bold">{script.title}</h4>
                    <p className="text-xs text-muted-foreground">{new Date(script.createdAt).toLocaleString()}</p>
                  </div>
                  <div className="flex items-center gap-1">
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-7 w-7 p-0"
                      onClick={() => downloadScript(script)}
                      title="Download script"
                    >
                      <Download className="w-3 h-3 text-muted-foreground" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-7 w-7 p-0"
                      onClick={() => deleteMutation.mutate(script.id)}
                    >
                      <Trash2 className="w-3 h-3 text-destructive" />
                    </Button>
                  </div>
                </div>
                <div className="p-3 rounded bg-black/30 border border-border/20 mt-2">
                  <p className="text-xs whitespace-pre-wrap font-mono leading-relaxed">{script.scriptContent}</p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

function MeetingUpload({ clientId }: { clientId: number }) {
  const queryClient = useQueryClient();
  const [title, setTitle] = useState("");
  const [transcript, setTranscript] = useState("");
  const [uploadMode, setUploadMode] = useState<"text" | "file">("text");
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const { data: recordings, isLoading } = useQuery<MeetingRecording[]>({
    queryKey: ["meetingRecordings", clientId],
    queryFn: async () => {
      const res = await fetch(`${BASE}/api/voice/recordings/${clientId}`);
      if (!res.ok) throw new Error("Failed");
      return res.json();
    },
  });

  const uploadMutation = useMutation({
    mutationFn: async () => {
      if (uploadMode === "file" && selectedFile) {
        const formData = new FormData();
        formData.append("file", selectedFile);
        formData.append("clientId", String(clientId));
        formData.append("title", title || selectedFile.name);
        const res = await fetch(`${BASE}/api/voice/upload-recording`, {
          method: "POST",
          body: formData,
        });
        if (!res.ok) throw new Error("Failed");
        return res.json();
      } else {
        const res = await fetch(`${BASE}/api/voice/upload-recording`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ clientId, title, transcript }),
        });
        if (!res.ok) throw new Error("Failed");
        return res.json();
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["meetingRecordings", clientId] });
      setTitle("");
      setTranscript("");
      setSelectedFile(null);
      if (fileInputRef.current) fileInputRef.current.value = "";
    },
  });

  const canSubmit = uploadMode === "file"
    ? !!selectedFile
    : !!title && !!transcript;

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base font-display flex items-center gap-2">
            <Upload className="w-4 h-4 text-primary" />
            Meeting Summary Generator
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="flex gap-2">
            <Button
              variant={uploadMode === "text" ? "default" : "outline"}
              size="sm"
              onClick={() => setUploadMode("text")}
              className="text-xs"
            >
              <FileText className="w-3 h-3 mr-1" />
              Paste Transcript
            </Button>
            <Button
              variant={uploadMode === "file" ? "default" : "outline"}
              size="sm"
              onClick={() => setUploadMode("file")}
              className="text-xs"
            >
              <Upload className="w-3 h-3 mr-1" />
              Upload Audio
            </Button>
          </div>

          {uploadMode === "file" ? (
            <>
              <p className="text-xs text-muted-foreground">
                Upload an audio/video file (MP3, MP4, M4A, WAV, WebM). It will be transcribed using AI and then summarized.
              </p>
              <Input
                placeholder="Meeting title (optional, defaults to filename)"
                value={title}
                onChange={e => setTitle(e.target.value)}
                className="text-sm"
              />
              <div
                className="border-2 border-dashed border-border/40 rounded-lg p-6 text-center cursor-pointer hover:border-primary/40 transition-colors"
                onClick={() => fileInputRef.current?.click()}
              >
                <input
                  ref={fileInputRef}
                  type="file"
                  accept=".mp3,.mp4,.m4a,.wav,.webm,.ogg,audio/*,video/mp4,video/webm"
                  className="hidden"
                  onChange={e => setSelectedFile(e.target.files?.[0] || null)}
                />
                {selectedFile ? (
                  <div className="space-y-1">
                    <Mic className="w-6 h-6 text-primary mx-auto" />
                    <p className="text-sm font-medium">{selectedFile.name}</p>
                    <p className="text-xs text-muted-foreground">
                      {(selectedFile.size / (1024 * 1024)).toFixed(1)} MB
                    </p>
                  </div>
                ) : (
                  <div className="space-y-1">
                    <Upload className="w-6 h-6 text-muted-foreground mx-auto" />
                    <p className="text-sm text-muted-foreground">Click to select audio file</p>
                    <p className="text-xs text-muted-foreground">Max 50 MB</p>
                  </div>
                )}
              </div>
            </>
          ) : (
            <>
              <p className="text-xs text-muted-foreground">
                Paste a meeting transcript to generate a structured summary with action items, decisions, and next steps.
              </p>
              <Input
                placeholder="Meeting title"
                value={title}
                onChange={e => setTitle(e.target.value)}
                className="text-sm"
              />
              <Textarea
                placeholder="Paste meeting transcript here..."
                value={transcript}
                onChange={e => setTranscript(e.target.value)}
                rows={6}
                className="text-sm font-mono"
              />
            </>
          )}

          <Button
            onClick={() => uploadMutation.mutate()}
            disabled={uploadMutation.isPending || !canSubmit}
            className="w-full"
            variant="glow"
          >
            {uploadMutation.isPending ? (
              <Loader2 className="w-4 h-4 animate-spin mr-2" />
            ) : uploadMode === "file" ? (
              <Upload className="w-4 h-4 mr-2" />
            ) : (
              <FileText className="w-4 h-4 mr-2" />
            )}
            {uploadMutation.isPending
              ? uploadMode === "file" ? "Transcribing & Summarizing..." : "Generating Summary..."
              : uploadMode === "file" ? "Upload & Transcribe" : "Generate Summary"
            }
          </Button>
        </CardContent>
      </Card>

      {isLoading && (
        <div className="flex justify-center py-4">
          <Loader2 className="w-5 h-5 animate-spin text-muted-foreground" />
        </div>
      )}

      {recordings && recordings.length > 0 && (
        <div className="space-y-3">
          {recordings.map(rec => {
            const summary = rec.summary as {
              attendees?: string[];
              decisions?: string[];
              actionItems?: { owner: string; task: string; deadline?: string }[];
              openQuestions?: string[];
              nextSteps?: string[];
              keyHighlights?: string;
            } | null;

            return (
              <Card key={rec.id} className="border-border/40">
                <CardContent className="p-4">
                  <div className="flex items-center justify-between mb-2">
                    <div>
                      <h4 className="text-sm font-bold">{rec.title}</h4>
                      <p className="text-xs text-muted-foreground">{new Date(rec.createdAt).toLocaleString()}</p>
                    </div>
                    <Badge variant={rec.status === "completed" ? "cyan" : "outline"} className="text-[10px]">
                      {rec.status}
                    </Badge>
                  </div>

                  {summary?.keyHighlights && (
                    <p className="text-xs mb-3 p-2 rounded bg-primary/5 border border-primary/10">{summary.keyHighlights}</p>
                  )}

                  {summary?.decisions && summary.decisions.length > 0 && (
                    <div className="mb-2">
                      <p className="text-[10px] font-tech uppercase text-muted-foreground mb-1">Decisions</p>
                      <ul className="list-disc list-inside text-xs space-y-0.5">
                        {summary.decisions.map((d, i) => <li key={i}>{d}</li>)}
                      </ul>
                    </div>
                  )}

                  {summary?.actionItems && summary.actionItems.length > 0 && (
                    <div className="mb-2">
                      <p className="text-[10px] font-tech uppercase text-muted-foreground mb-1">Action Items</p>
                      <ul className="space-y-1">
                        {summary.actionItems.map((item, i) => (
                          <li key={i} className="text-xs flex items-start gap-1">
                            <span className="text-primary">-</span>
                            <span><strong>{item.owner}:</strong> {item.task} {item.deadline && <span className="text-muted-foreground">({item.deadline})</span>}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {summary?.nextSteps && summary.nextSteps.length > 0 && (
                    <div>
                      <p className="text-[10px] font-tech uppercase text-muted-foreground mb-1">Next Steps</p>
                      <ul className="list-disc list-inside text-xs space-y-0.5">
                        {summary.nextSteps.map((s, i) => <li key={i}>{s}</li>)}
                      </ul>
                    </div>
                  )}
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}

export function CallsTab({ clientId }: { clientId: number }) {
  const queryClient = useQueryClient();
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [activeSection, setActiveSection] = useState<"calls" | "scripts" | "meetings">("calls");
  const [generatingId, setGeneratingId] = useState<number | null>(null);

  const { data: calls, isLoading } = useQuery<CallLog[]>({
    queryKey: ["voiceCalls", clientId, dateFrom, dateTo, statusFilter],
    queryFn: async () => {
      const params = new URLSearchParams();
      if (dateFrom) params.set("dateFrom", dateFrom);
      if (dateTo) params.set("dateTo", dateTo);
      if (statusFilter) params.set("status", statusFilter);
      const res = await fetch(`${BASE}/api/voice/calls/${clientId}?${params}`);
      if (!res.ok) throw new Error("Failed");
      return res.json();
    },
  });

  const debriefMutation = useMutation({
    mutationFn: async (callLogId: number) => {
      setGeneratingId(callLogId);
      const res = await fetch(`${BASE}/api/voice/debrief/${callLogId}`, { method: "POST" });
      if (!res.ok) throw new Error("Failed");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["voiceCalls", clientId] });
      setGeneratingId(null);
    },
    onError: () => setGeneratingId(null),
  });

  return (
    <div className="space-y-6">
      <div className="flex gap-2 p-1 rounded-lg bg-secondary/30 border border-border/30 w-fit">
        <button
          onClick={() => setActiveSection("calls")}
          className={`flex items-center gap-1.5 px-4 py-2 rounded text-xs font-tech transition-all ${
            activeSection === "calls"
              ? "bg-primary/20 text-primary border border-primary/30"
              : "text-muted-foreground hover:text-foreground"
          }`}
        >
          <Phone className="w-3.5 h-3.5" />
          Call History
        </button>
        <button
          onClick={() => setActiveSection("scripts")}
          className={`flex items-center gap-1.5 px-4 py-2 rounded text-xs font-tech transition-all ${
            activeSection === "scripts"
              ? "bg-primary/20 text-primary border border-primary/30"
              : "text-muted-foreground hover:text-foreground"
          }`}
        >
          <Mic className="w-3.5 h-3.5" />
          Scripts
        </button>
        <button
          onClick={() => setActiveSection("meetings")}
          className={`flex items-center gap-1.5 px-4 py-2 rounded text-xs font-tech transition-all ${
            activeSection === "meetings"
              ? "bg-primary/20 text-primary border border-primary/30"
              : "text-muted-foreground hover:text-foreground"
          }`}
        >
          <Upload className="w-3.5 h-3.5" />
          Meetings
        </button>
      </div>

      {activeSection === "calls" && (
        <div className="space-y-4">
          <div className="flex gap-3 items-end flex-wrap">
            <div className="space-y-1">
              <label className="text-[10px] font-tech uppercase text-muted-foreground">From</label>
              <Input
                type="date"
                value={dateFrom}
                onChange={e => setDateFrom(e.target.value)}
                className="text-xs h-8 w-40"
              />
            </div>
            <div className="space-y-1">
              <label className="text-[10px] font-tech uppercase text-muted-foreground">To</label>
              <Input
                type="date"
                value={dateTo}
                onChange={e => setDateTo(e.target.value)}
                className="text-xs h-8 w-40"
              />
            </div>
            <div className="space-y-1">
              <label className="text-[10px] font-tech uppercase text-muted-foreground">Status</label>
              <select
                value={statusFilter}
                onChange={e => setStatusFilter(e.target.value)}
                className="h-8 text-xs rounded border border-border bg-background px-2 w-36"
              >
                <option value="">All Statuses</option>
                <option value="completed">Completed</option>
                <option value="in-progress">In Progress</option>
                <option value="missed">Missed</option>
                <option value="failed">Failed</option>
                <option value="voicemail">Voicemail</option>
              </select>
            </div>
            {(dateFrom || dateTo || statusFilter) && (
              <Button variant="ghost" size="sm" className="h-8 text-xs" onClick={() => { setDateFrom(""); setDateTo(""); setStatusFilter(""); }}>
                Clear Filters
              </Button>
            )}
          </div>

          {isLoading ? (
            <div className="flex justify-center py-8">
              <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
            </div>
          ) : calls && calls.length > 0 ? (
            <div className="space-y-3">
              {calls.map(call => (
                <CallCard
                  key={call.id}
                  call={call}
                  onGenerateDebrief={(id) => debriefMutation.mutate(id)}
                  isGenerating={generatingId === call.id}
                />
              ))}
            </div>
          ) : (
            <Card className="border-border/40">
              <CardContent className="p-8 text-center">
                <Phone className="w-8 h-8 text-muted-foreground mx-auto mb-3" />
                <p className="text-muted-foreground text-sm font-tech">No calls recorded yet</p>
                <p className="text-muted-foreground text-xs mt-1">
                  Calls will appear here once the AI Receptionist handles inbound calls for this client.
                </p>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      {activeSection === "scripts" && <ScriptGenerator clientId={clientId} />}

      {activeSection === "meetings" && <MeetingUpload clientId={clientId} />}
    </div>
  );
}
